export default [
  {
    id: "ford-escort-rs-cosworth",
    brand: "Ford",
    model: "Escort RS Cosworth",
    year: 1992,
    country: "United Kingdom",
    bodyType: "Hatchback",
    engine: "2.0L Turbo Inline-Four (Cosworth YBT)",
    engineType: "Turbo",
    horsepower: 227,
    torqueNm: 304,
    zeroToHundred: 5.7,
    topSpeed: 232,
    drivetrain: "AWD",
    weightKg: 1275,
    perfCategory: "Sport",
    categories: ["European", "Track Cars"],
    description: "Homologation special with a whale-tail spoiler and Cosworth turbo four, the Escort RS Cosworth brought rally-bred all-wheel-drive fury to British roads.",
    query: "Ford Escort RS Cosworth",
    fallbackQuery: "Ford Escort Cosworth"
  },
  {
    id: "ford-sierra-rs500-cosworth",
    brand: "Ford",
    model: "Sierra RS500 Cosworth",
    year: 1987,
    country: "United Kingdom",
    bodyType: "Hatchback",
    engine: "2.0L Turbo Inline-Four (Cosworth YBD)",
    engineType: "Turbo",
    horsepower: 224,
    torqueNm: 279,
    zeroToHundred: 6.0,
    topSpeed: 248,
    drivetrain: "RWD",
    weightKg: 1206,
    perfCategory: "Sport",
    categories: ["European", "Track Cars"],
    description: "Limited to 500 road cars to homologate the Group A racer, the Sierra RS500 Cosworth packed a 224-horsepower turbo four and a legendary racing pedigree.",
    query: "Ford Sierra RS500 Cosworth",
    fallbackQuery: "Ford Sierra RS Cosworth"
  },
  {
    id: "ford-focus-rs-mk3",
    brand: "Ford",
    model: "Focus RS (Mk3)",
    year: 2016,
    country: "United Kingdom",
    bodyType: "Hatchback",
    engine: "2.3L Turbo Inline-Four (EcoBoost)",
    engineType: "Turbo",
    horsepower: 350,
    torqueNm: 470,
    zeroToHundred: 4.7,
    topSpeed: 266,
    drivetrain: "AWD",
    weightKg: 1575,
    perfCategory: "Sport",
    categories: ["European", "Track Cars"],
    description: "Ford Performance gave the Mk3 Focus RS a 350-horsepower EcoBoost four, torque-vectoring all-wheel drive and a Drift Mode that made it a hot hatch icon.",
    query: "Ford Focus RS Mk3",
    fallbackQuery: "Ford Focus RS 2016"
  },
  {
    id: "ford-fiesta-st-mk8",
    brand: "Ford",
    model: "Fiesta ST (Mk8)",
    year: 2018,
    country: "United Kingdom",
    bodyType: "Hatchback",
    engine: "1.5L Turbo Inline-Three (EcoBoost)",
    engineType: "Turbo",
    horsepower: 200,
    torqueNm: 290,
    zeroToHundred: 6.5,
    topSpeed: 232,
    drivetrain: "FWD",
    weightKg: 1262,
    perfCategory: "Sport",
    categories: ["European", "Track Cars"],
    description: "The Mk8 Fiesta ST swapped to a punchy 200-horsepower three-cylinder and a clever limited-slip differential, delivering giant-killing thrills in a compact package.",
    query: "Ford Fiesta ST Mk8",
    fallbackQuery: "Ford Fiesta ST 2018"
  },
  {
    id: "ford-mustang-boss-302",
    brand: "Ford",
    model: "Mustang Boss 302",
    year: 1969,
    country: "United States",
    bodyType: "Coupe",
    engine: "4.9L V8 (Boss 302)",
    engineType: "Naturally Aspirated",
    horsepower: 290,
    torqueNm: 393,
    zeroToHundred: 6.5,
    topSpeed: 214,
    drivetrain: "RWD",
    weightKg: 1550,
    perfCategory: "Sport",
    categories: ["Muscle", "Classic Cars"],
    description: "Built to homologate Ford's Trans-Am racer, the 1969 Boss 302 Mustang paired a high-revving 290-horsepower V8 with track-tuned suspension and bold graphics.",
    query: "Ford Mustang Boss 302 1969",
    fallbackQuery: "Ford Mustang Boss 302"
  },
  {
    id: "ford-capri-2-8i",
    brand: "Ford",
    model: "Capri 2.8i",
    year: 1981,
    country: "United Kingdom",
    bodyType: "Coupe",
    engine: "2.8L V6 (Cologne)",
    engineType: "Naturally Aspirated",
    horsepower: 160,
    torqueNm: 221,
    zeroToHundred: 8.2,
    topSpeed: 210,
    drivetrain: "RWD",
    weightKg: 1210,
    perfCategory: "Sport",
    categories: ["European", "Classic Cars"],
    description: "The fuel-injected Capri 2.8i was the fastest European Capri, its Bosch-injected Cologne V6 and rear-drive chassis making it a cult British performance coupe.",
    query: "Ford Capri 2.8 Injection",
    fallbackQuery: "Ford Capri Mk3"
  },
  {
    id: "ford-f-150-raptor",
    brand: "Ford",
    model: "F-150 Raptor",
    year: 2021,
    country: "United States",
    bodyType: "Pickup",
    engine: "3.5L Twin-Turbo V6 (EcoBoost)",
    engineType: "Twin-Turbo",
    horsepower: 450,
    torqueNm: 691,
    zeroToHundred: 5.2,
    topSpeed: 180,
    drivetrain: "AWD",
    weightKg: 2600,
    perfCategory: "Sport",
    categories: ["Muscle", "Track Cars"],
    description: "Ford's desert-racing pickup returns with a 450-horsepower twin-turbo V6, long-travel Fox shocks and 37-inch tires built to fly across open terrain.",
    query: "Ford F-150 Raptor 2021",
    fallbackQuery: "Ford F-150 Raptor"
  },
  {
    id: "ford-bronco",
    brand: "Ford",
    model: "Bronco",
    year: 2021,
    country: "United States",
    bodyType: "SUV",
    engine: "2.7L Twin-Turbo V6 (EcoBoost)",
    engineType: "Twin-Turbo",
    horsepower: 330,
    torqueNm: 563,
    zeroToHundred: 6.5,
    topSpeed: 161,
    drivetrain: "AWD",
    weightKg: 2073,
    perfCategory: "Sport",
    categories: ["Muscle", "Track Cars"],
    description: "Reviving a legendary nameplate, the 2021 Bronco pairs a 330-horsepower twin-turbo V6 with removable doors and roof for genuine off-road adventure.",
    query: "Ford Bronco 2021",
    fallbackQuery: "Ford Bronco Wildtrak"
  },
  {
    id: "chevrolet-bel-air",
    brand: "Chevrolet",
    model: "Bel Air",
    year: 1957,
    country: "United States",
    bodyType: "Sedan",
    engine: "4.6L V8 (283 Small-Block)",
    engineType: "Naturally Aspirated",
    horsepower: 220,
    torqueNm: 407,
    zeroToHundred: 8.5,
    topSpeed: 177,
    drivetrain: "RWD",
    weightKg: 1580,
    perfCategory: "Luxury",
    categories: ["Classic Cars", "Muscle"],
    description: "The definitive Tri-Five Chevrolet, the 1957 Bel Air flaunted chrome-laden styling, tail fins and an optional fuel-injected 283 V8 that made it a cultural touchstone.",
    query: "Chevrolet Bel Air 1957",
    fallbackQuery: "1957 Chevrolet Bel Air"
  },
  {
    id: "chevrolet-impala-ss",
    brand: "Chevrolet",
    model: "Impala SS",
    year: 1964,
    country: "United States",
    bodyType: "Coupe",
    engine: "6.7L V8 (409 Turbo-Fire)",
    engineType: "Naturally Aspirated",
    horsepower: 425,
    torqueNm: 576,
    zeroToHundred: 6.2,
    topSpeed: 224,
    drivetrain: "RWD",
    weightKg: 1692,
    perfCategory: "Sport",
    categories: ["Muscle", "Classic Cars"],
    description: "The 409-powered Impala SS was Chevrolet's full-size street brawler, its dual-quad big-block V8 and bucket-seat interior immortalized in song and drag strip legend.",
    query: "Chevrolet Impala SS 1964",
    fallbackQuery: "Chevrolet Impala 409"
  },
  {
    id: "chevrolet-chevelle-ss-454",
    brand: "Chevrolet",
    model: "Chevelle SS 454",
    year: 1970,
    country: "United States",
    bodyType: "Coupe",
    engine: "7.4L V8 (LS6 454)",
    engineType: "Naturally Aspirated",
    horsepower: 450,
    torqueNm: 678,
    zeroToHundred: 5.8,
    topSpeed: 210,
    drivetrain: "RWD",
    weightKg: 1740,
    perfCategory: "Sport",
    categories: ["Muscle", "Classic Cars"],
    description: "The LS6 Chevelle SS 454 was the peak of the muscle car wars, its 450-horsepower big-block making it the most powerful Chevrolet of its era.",
    query: "Chevrolet Chevelle SS 454",
    fallbackQuery: "1970 Chevrolet Chevelle SS"
  },
  {
    id: "chevrolet-camaro-ss",
    brand: "Chevrolet",
    model: "Camaro SS",
    year: 1969,
    country: "United States",
    bodyType: "Coupe",
    engine: "6.5L V8 (396 Turbo-Jet)",
    engineType: "Naturally Aspirated",
    horsepower: 375,
    torqueNm: 563,
    zeroToHundred: 6.8,
    topSpeed: 220,
    drivetrain: "RWD",
    weightKg: 1719,
    perfCategory: "Sport",
    categories: ["Muscle", "Classic Cars"],
    description: "The 1969 Camaro SS 396 combined sharp styling with a 375-horsepower big-block, cementing the pony car as a perennial American performance favorite.",
    query: "Chevrolet Camaro SS 1969",
    fallbackQuery: "1969 Chevrolet Camaro SS 396"
  },
  {
    id: "chevrolet-camaro-zl1",
    brand: "Chevrolet",
    model: "Camaro ZL1",
    year: 2017,
    country: "United States",
    bodyType: "Coupe",
    engine: "6.2L Supercharged V8 (LT4)",
    engineType: "Supercharged",
    horsepower: 650,
    torqueNm: 881,
    zeroToHundred: 3.5,
    topSpeed: 318,
    drivetrain: "RWD",
    weightKg: 1795,
    perfCategory: "Super",
    categories: ["Muscle", "Track Cars"],
    description: "The sixth-generation Camaro ZL1 channels a supercharged 650-horsepower LT4 V8 through magnetic ride control, making it a track-ready American muscle monster.",
    query: "Chevrolet Camaro ZL1",
    fallbackQuery: "Chevrolet Camaro ZL1 2017"
  },
  {
    id: "chevrolet-corvette-c2-sting-ray",
    brand: "Chevrolet",
    model: "Corvette C2 Sting Ray",
    year: 1963,
    country: "United States",
    bodyType: "Coupe",
    engine: "5.4L V8 (327 Small-Block)",
    engineType: "Naturally Aspirated",
    horsepower: 340,
    torqueNm: 461,
    zeroToHundred: 6.0,
    topSpeed: 240,
    drivetrain: "RWD",
    weightKg: 1442,
    perfCategory: "Sport",
    categories: ["Classic Cars", "Muscle"],
    description: "The split-window 1963 Sting Ray introduced independent rear suspension and razor-edge styling, its 340-horsepower 327 V8 making it a genuine sports car.",
    query: "Chevrolet Corvette C2 Sting Ray",
    fallbackQuery: "1963 Chevrolet Corvette Sting Ray"
  },
  {
    id: "chevrolet-corvette-c3-stingray",
    brand: "Chevrolet",
    model: "Corvette C3 Stingray",
    year: 1968,
    country: "United States",
    bodyType: "Coupe",
    engine: "7.0L V8 (427 Turbo-Jet L71)",
    engineType: "Naturally Aspirated",
    horsepower: 435,
    torqueNm: 624,
    zeroToHundred: 5.5,
    topSpeed: 258,
    drivetrain: "RWD",
    weightKg: 1560,
    perfCategory: "Sport",
    categories: ["Muscle", "Classic Cars"],
    description: "The shark-nosed C3 Stingray debuted in 1968 with optional T-tops and a thundering 435-horsepower 427 big-block, blending dramatic curves with brutal straight-line speed.",
    query: "Chevrolet Corvette C3 Stingray",
    fallbackQuery: "1968 Chevrolet Corvette 427"
  },
  {
    id: "chevrolet-corvette-z06-c7",
    brand: "Chevrolet",
    model: "Corvette Z06 (C7)",
    year: 2014,
    country: "United States",
    bodyType: "Coupe",
    engine: "6.2L Supercharged V8 (LT4)",
    engineType: "Supercharged",
    horsepower: 650,
    torqueNm: 881,
    zeroToHundred: 3.7,
    topSpeed: 315,
    drivetrain: "RWD",
    weightKg: 1598,
    perfCategory: "Super",
    categories: ["Muscle", "Track Cars"],
    description: "The C7 Corvette Z06 packed a supercharged 650-horsepower LT4 and an optional Z07 track package, delivering supercar pace for a fraction of the European price.",
    query: "Chevrolet Corvette Z06 C7",
    fallbackQuery: "Chevrolet Corvette Z06 2015"
  },
  {
    id: "chevrolet-silverado",
    brand: "Chevrolet",
    model: "Silverado",
    year: 2019,
    country: "United States",
    bodyType: "Pickup",
    engine: "6.2L V8 (EcoTec3 L87)",
    engineType: "Naturally Aspirated",
    horsepower: 420,
    torqueNm: 624,
    zeroToHundred: 5.4,
    topSpeed: 180,
    drivetrain: "AWD",
    weightKg: 2400,
    perfCategory: "Sport",
    categories: ["Muscle", "Track Cars"],
    description: "The redesigned 2019 Silverado offered a 420-horsepower 6.2-liter V8 and a lighter high-strength steel body, blending full-size truck capability with surprising pace.",
    query: "Chevrolet Silverado 2019",
    fallbackQuery: "Chevrolet Silverado 1500"
  },
  {
    id: "dodge-charger-1969",
    brand: "Dodge",
    model: "Charger",
    year: 1969,
    country: "United States",
    bodyType: "Coupe",
    engine: "7.0L V8 (426 Hemi)",
    engineType: "Naturally Aspirated",
    horsepower: 425,
    torqueNm: 664,
    zeroToHundred: 5.7,
    topSpeed: 225,
    drivetrain: "RWD",
    weightKg: 1665,
    perfCategory: "Sport",
    categories: ["Muscle", "Classic Cars"],
    description: "With its hidden headlights and optional 426 Hemi, the 1969 Charger became a muscle car legend, its 425-horsepower V8 and sleek fastback shape instantly recognizable.",
    query: "Dodge Charger 1969",
    fallbackQuery: "1969 Dodge Charger R/T"
  },
  {
    id: "dodge-super-bee",
    brand: "Dodge",
    model: "Super Bee",
    year: 1970,
    country: "United States",
    bodyType: "Coupe",
    engine: "7.2L V8 (440 Six Pack)",
    engineType: "Naturally Aspirated",
    horsepower: 390,
    torqueNm: 664,
    zeroToHundred: 6.0,
    topSpeed: 188,
    drivetrain: "RWD",
    weightKg: 1730,
    perfCategory: "Sport",
    categories: ["Muscle", "Classic Cars"],
    description: "The 1970 Super Bee wore a bold twin-looped front bumper and offered a 390-horsepower 440 Six Pack, making it a formidable Mopar street brawler.",
    query: "Dodge Super Bee 1970",
    fallbackQuery: "Dodge Coronet Super Bee"
  },
  {
    id: "dodge-neon-srt-4",
    brand: "Dodge",
    model: "Neon SRT-4",
    year: 2003,
    country: "United States",
    bodyType: "Sedan",
    engine: "2.4L Turbo Inline-Four",
    engineType: "Turbo",
    horsepower: 215,
    torqueNm: 332,
    zeroToHundred: 6.5,
    topSpeed: 246,
    drivetrain: "FWD",
    weightKg: 1347,
    perfCategory: "Sport",
    categories: ["Muscle", "Track Cars"],
    description: "The Neon SRT-4 turned Dodge's humble economy sedan into a 215-horsepower turbocharged pocket rocket, delivering brutal front-wheel-drive acceleration for a bargain price.",
    query: "Dodge Neon SRT-4",
    fallbackQuery: "Dodge SRT-4"
  },
  {
    id: "dodge-viper-gts",
    brand: "Dodge",
    model: "Viper GTS",
    year: 1996,
    country: "United States",
    bodyType: "Coupe",
    engine: "8.0L V10",
    engineType: "Naturally Aspirated",
    horsepower: 450,
    torqueNm: 664,
    zeroToHundred: 4.4,
    topSpeed: 285,
    drivetrain: "RWD",
    weightKg: 1531,
    perfCategory: "Super",
    categories: ["Muscle", "Track Cars"],
    description: "The 1996 Viper GTS coupe wrapped an 8.0-liter 450-horsepower V10 in a curvaceous double-bubble roof, becoming the definitive American supercar of the nineties.",
    query: "Dodge Viper GTS",
    fallbackQuery: "Dodge Viper GTS 1996"
  },
  {
    id: "dodge-viper-srt-10-acr",
    brand: "Dodge",
    model: "Viper SRT-10 ACR",
    year: 2008,
    country: "United States",
    bodyType: "Coupe",
    engine: "8.4L V10",
    engineType: "Naturally Aspirated",
    horsepower: 600,
    torqueNm: 760,
    zeroToHundred: 3.8,
    topSpeed: 296,
    drivetrain: "RWD",
    weightKg: 1552,
    perfCategory: "Super",
    categories: ["Muscle", "Track Cars"],
    description: "The Viper SRT-10 ACR added aggressive aero, adjustable KW suspension and a 600-horsepower 8.4-liter V10, setting production car lap records at tracks worldwide.",
    query: "Dodge Viper SRT-10 ACR",
    fallbackQuery: "Dodge Viper ACR"
  },
  {
    id: "dodge-challenger-srt-demon",
    brand: "Dodge",
    model: "Challenger SRT Demon",
    year: 2018,
    country: "United States",
    bodyType: "Coupe",
    engine: "6.2L Supercharged V8 (Hellcat Demon)",
    engineType: "Supercharged",
    horsepower: 840,
    torqueNm: 1044,
    zeroToHundred: 2.3,
    topSpeed: 270,
    drivetrain: "RWD",
    weightKg: 1941,
    perfCategory: "Hyper",
    categories: ["Muscle", "Track Cars"],
    description: "Built for the drag strip, the Challenger SRT Demon produced 840 horsepower on race fuel and ran the quarter mile in 9.65 seconds.",
    query: "Dodge Challenger SRT Demon",
    fallbackQuery: "Dodge Challenger Demon 2018"
  },
  {
    id: "dodge-charger-srt-hellcat",
    brand: "Dodge",
    model: "Charger SRT Hellcat",
    year: 2015,
    country: "United States",
    bodyType: "Sedan",
    engine: "6.2L Supercharged V8 (Hellcat)",
    engineType: "Supercharged",
    horsepower: 707,
    torqueNm: 881,
    zeroToHundred: 3.8,
    topSpeed: 329,
    drivetrain: "RWD",
    weightKg: 2068,
    perfCategory: "Super",
    categories: ["Muscle", "Track Cars"],
    description: "The 2015 Charger SRT Hellcat became the world's most powerful production sedan, its 707-horsepower supercharged Hemi and 204 mph top speed rewriting four-door expectations.",
    query: "Dodge Charger SRT Hellcat",
    fallbackQuery: "Dodge Charger Hellcat 2015"
  },
  {
    id: "dodge-durango-srt-hellcat",
    brand: "Dodge",
    model: "Durango SRT Hellcat",
    year: 2021,
    country: "United States",
    bodyType: "SUV",
    engine: "6.2L Supercharged V8 (Hellcat)",
    engineType: "Supercharged",
    horsepower: 710,
    torqueNm: 875,
    zeroToHundred: 3.5,
    topSpeed: 290,
    drivetrain: "AWD",
    weightKg: 2585,
    perfCategory: "Super",
    categories: ["Muscle", "Track Cars"],
    description: "Offered for a single model year, the Durango SRT Hellcat packed 710 supercharged horsepower into a three-row SUV, hitting 100 km/h in just 3.5 seconds.",
    query: "Dodge Durango SRT Hellcat",
    fallbackQuery: "Dodge Durango Hellcat 2021"
  },
  {
    id: "dodge-ram-1500-trx",
    brand: "Dodge",
    model: "Ram 1500 TRX",
    year: 2021,
    country: "United States",
    bodyType: "Pickup",
    engine: "6.2L Supercharged V8 (Hellcat)",
    engineType: "Supercharged",
    horsepower: 702,
    torqueNm: 881,
    zeroToHundred: 4.5,
    topSpeed: 190,
    drivetrain: "AWD",
    weightKg: 2880,
    perfCategory: "Super",
    categories: ["Muscle", "Track Cars"],
    description: "The Ram 1500 TRX stuffed a 702-horsepower Hellcat V8 into a high-riding off-road pickup, becoming the quickest and most powerful mass-produced truck of its time.",
    query: "Ram 1500 TRX",
    fallbackQuery: "Ram TRX 2021"
  }
];
