export default [
  {
    id: "vw-golf-gti-mk1",
    brand: "Volkswagen",
    model: "Golf GTI (Mk1)",
    year: 1976,
    country: "Germany",
    bodyType: "Hatchback",
    engine: "1.6L Inline-Four (EA827)",
    engineType: "Naturally Aspirated",
    horsepower: 110,
    torqueNm: 140,
    zeroToHundred: 9.2,
    topSpeed: 182,
    drivetrain: "FWD",
    weightKg: 810,
    perfCategory: "Sport",
    categories: ["European", "Classic Cars"],
    description: "The original hot hatch, whose fuel-injected 1.6 and tartan seats invented a whole genre of affordable everyday performance.",
    query: "Volkswagen Golf I GTI",
    fallbackQuery: "VW Golf Mk1 GTI"
  },
  {
    id: "vw-golf-gti-mk2-16v",
    brand: "Volkswagen",
    model: "Golf GTI 16V (Mk2)",
    year: 1986,
    country: "Germany",
    bodyType: "Hatchback",
    engine: "1.8L 16-Valve Inline-Four (KR)",
    engineType: "Naturally Aspirated",
    horsepower: 139,
    torqueNm: 168,
    zeroToHundred: 8.6,
    topSpeed: 208,
    drivetrain: "FWD",
    weightKg: 1010,
    perfCategory: "Sport",
    categories: ["European"],
    description: "The 16-valve Mk2 GTI added a screaming twin-cam head and red badges, sharpening the hot hatch formula into a genuine driver's tool.",
    query: "Volkswagen Golf II GTI 16V",
    fallbackQuery: "VW Golf Mk2 GTI"
  },
  {
    id: "vw-golf-r-mk8",
    brand: "Volkswagen",
    model: "Golf R (Mk8)",
    year: 2021,
    country: "Germany",
    bodyType: "Hatchback",
    engine: "2.0L Turbo Inline-Four (EA888)",
    engineType: "Turbo",
    horsepower: 320,
    torqueNm: 420,
    zeroToHundred: 4.7,
    topSpeed: 250,
    drivetrain: "AWD",
    weightKg: 1551,
    perfCategory: "Sport",
    categories: ["European"],
    description: "The Mk8 Golf R pairs a torque-vectoring rear diff with 320 turbocharged horses, making it the most clinical all-weather hot hatch yet.",
    query: "Volkswagen Golf VIII R",
    fallbackQuery: "Volkswagen Golf R"
  },
  {
    id: "vw-polo-gti-aw",
    brand: "Volkswagen",
    model: "Polo GTI (AW)",
    year: 2018,
    country: "Germany",
    bodyType: "Hatchback",
    engine: "2.0L Turbo Inline-Four (EA888)",
    engineType: "Turbo",
    horsepower: 200,
    torqueNm: 320,
    zeroToHundred: 6.7,
    topSpeed: 237,
    drivetrain: "FWD",
    weightKg: 1355,
    perfCategory: "Sport",
    categories: ["European"],
    description: "The sixth-generation Polo GTI squeezed a 2.0-litre turbo and 200 horsepower into a supermini shell for giant-killing pace.",
    query: "Volkswagen Polo GTI AW",
    fallbackQuery: "Volkswagen Polo GTI"
  },
  {
    id: "vw-scirocco-r",
    brand: "Volkswagen",
    model: "Scirocco R",
    year: 2009,
    country: "Germany",
    bodyType: "Coupe",
    engine: "2.0L Turbo Inline-Four (EA113)",
    engineType: "Turbo",
    horsepower: 265,
    torqueNm: 350,
    zeroToHundred: 6.0,
    topSpeed: 250,
    drivetrain: "FWD",
    weightKg: 1289,
    perfCategory: "Sport",
    categories: ["European"],
    description: "The Scirocco R wrapped a 265-horsepower turbo four in a low, wide coupe body that revived Volkswagen's forgotten sports nameplate.",
    query: "Volkswagen Scirocco R",
    fallbackQuery: "VW Scirocco R"
  },
  {
    id: "vw-arteon-r",
    brand: "Volkswagen",
    model: "Arteon R",
    year: 2021,
    country: "Germany",
    bodyType: "Sedan",
    engine: "2.0L Turbo Inline-Four (EA888)",
    engineType: "Turbo",
    horsepower: 320,
    torqueNm: 420,
    zeroToHundred: 4.9,
    topSpeed: 270,
    drivetrain: "AWD",
    weightKg: 1768,
    perfCategory: "Sport",
    categories: ["European"],
    description: "Volkswagen's sleek four-door fastback gained the Golf R's 320-horsepower drivetrain and a drift-happy rear torque-vectoring system.",
    query: "Volkswagen Arteon R",
    fallbackQuery: "VW Arteon R"
  },
  {
    id: "vw-phaeton-w12",
    brand: "Volkswagen",
    model: "Phaeton W12",
    year: 2002,
    country: "Germany",
    bodyType: "Sedan",
    engine: "6.0L W12 (BAN)",
    engineType: "Naturally Aspirated",
    horsepower: 420,
    torqueNm: 550,
    zeroToHundred: 6.1,
    topSpeed: 250,
    drivetrain: "AWD",
    weightKg: 2356,
    perfCategory: "Luxury",
    categories: ["European", "Luxury"],
    description: "Volkswagen's audacious luxury flagship hid a 420-horsepower W12 and hand-stitched cabin behind a deliberately understated badge.",
    query: "Volkswagen Phaeton W12",
    fallbackQuery: "VW Phaeton"
  },
  {
    id: "vw-beetle-type-1",
    brand: "Volkswagen",
    model: "Beetle (Type 1)",
    year: 1967,
    country: "Germany",
    bodyType: "Coupe",
    engine: "1.5L Air-Cooled Flat-Four (1500)",
    engineType: "Naturally Aspirated",
    horsepower: 53,
    torqueNm: 106,
    zeroToHundred: 20.0,
    topSpeed: 125,
    drivetrain: "RWD",
    weightKg: 840,
    perfCategory: "Luxury",
    categories: ["European", "Classic Cars"],
    description: "The 1967 Beetle brought a bigger 1500 engine and 12-volt electrics to the world's most beloved rear-engined people's car.",
    query: "Volkswagen Beetle 1500",
    fallbackQuery: "Volkswagen Type 1 Beetle"
  },
  {
    id: "vw-id4",
    brand: "Volkswagen",
    model: "ID.4",
    year: 2021,
    country: "Germany",
    bodyType: "SUV",
    engine: "Rear Electric Motor (APP 310)",
    engineType: "Electric",
    horsepower: 204,
    torqueNm: 310,
    zeroToHundred: 8.5,
    topSpeed: 160,
    drivetrain: "RWD",
    weightKg: 2024,
    perfCategory: "Luxury",
    categories: ["Electric", "European"],
    description: "Volkswagen's first global electric SUV, the ID.4 traded combustion for a silent 204-horsepower rear motor and 500 kilometres of range.",
    query: "Volkswagen ID.4",
    fallbackQuery: "VW ID4"
  },
  {
    id: "porsche-356-speedster",
    brand: "Porsche",
    model: "356 Speedster",
    year: 1955,
    country: "Germany",
    bodyType: "Roadster",
    engine: "1.6L Air-Cooled Flat-Four (Type 616)",
    engineType: "Naturally Aspirated",
    horsepower: 60,
    torqueNm: 110,
    zeroToHundred: 13.9,
    topSpeed: 158,
    drivetrain: "RWD",
    weightKg: 762,
    perfCategory: "Sport",
    categories: ["European", "Classic Cars"],
    description: "Built for California sun, the stripped-back 356 Speedster paired a low windscreen with a featherweight 60-horsepower flat-four.",
    query: "Porsche 356 Speedster",
    fallbackQuery: "Porsche 356 A Speedster"
  },
  {
    id: "porsche-959",
    brand: "Porsche",
    model: "959",
    year: 1986,
    country: "Germany",
    bodyType: "Coupe",
    engine: "2.8L Twin-Turbo Flat-Six (Type 935/76)",
    engineType: "Twin-Turbo",
    horsepower: 450,
    torqueNm: 500,
    zeroToHundred: 3.7,
    topSpeed: 317,
    drivetrain: "AWD",
    weightKg: 1450,
    perfCategory: "Super",
    categories: ["European", "Classic Cars"],
    description: "The 959 fused twin turbos, all-wheel drive and adjustable suspension into a 1980s Group B refugee that rewrote supercar rules.",
    query: "Porsche 959",
    fallbackQuery: "Porsche 959 Gruppe B"
  },
  {
    id: "porsche-carrera-gt",
    brand: "Porsche",
    model: "Carrera GT",
    year: 2004,
    country: "Germany",
    bodyType: "Convertible",
    engine: "5.7L Naturally Aspirated V10",
    engineType: "Naturally Aspirated",
    horsepower: 612,
    torqueNm: 590,
    zeroToHundred: 3.9,
    topSpeed: 330,
    drivetrain: "RWD",
    weightKg: 1380,
    perfCategory: "Hyper",
    categories: ["Supercars", "European"],
    description: "A Le Mans V10 shoehorned into a carbon monocoque, the Carrera GT remains one of the most demanding analogue hypercars ever built.",
    query: "Porsche Carrera GT",
    fallbackQuery: "Porsche Carrera GT 980"
  },
  {
    id: "porsche-918-spyder",
    brand: "Porsche",
    model: "918 Spyder",
    year: 2013,
    country: "Germany",
    bodyType: "Roadster",
    engine: "4.6L V8 Hybrid",
    engineType: "Hybrid",
    horsepower: 887,
    torqueNm: 1280,
    zeroToHundred: 2.6,
    topSpeed: 345,
    drivetrain: "AWD",
    weightKg: 1674,
    perfCategory: "Hyper",
    categories: ["Supercars", "European", "Electric"],
    description: "The 918 Spyder combined a 9000-rpm V8 with two electric motors, delivering 887 horsepower and a Nurburgring record for hybrids.",
    query: "Porsche 918 Spyder",
    fallbackQuery: "Porsche 918"
  },
  {
    id: "porsche-911-turbo-s-992",
    brand: "Porsche",
    model: "911 Turbo S (992)",
    year: 2020,
    country: "Germany",
    bodyType: "Coupe",
    engine: "3.7L Twin-Turbo Flat-Six (9A2 Evo)",
    engineType: "Twin-Turbo",
    horsepower: 650,
    torqueNm: 800,
    zeroToHundred: 2.7,
    topSpeed: 330,
    drivetrain: "AWD",
    weightKg: 1640,
    perfCategory: "Super",
    categories: ["Supercars", "European"],
    description: "The 992 Turbo S delivers 650 horsepower and all-weather traction so complete it makes hypercar acceleration feel routine.",
    query: "Porsche 911 Turbo S 992",
    fallbackQuery: "Porsche 911 Turbo S"
  },
  {
    id: "porsche-911-gt2-rs-991",
    brand: "Porsche",
    model: "911 GT2 RS (991)",
    year: 2017,
    country: "Germany",
    bodyType: "Coupe",
    engine: "3.8L Twin-Turbo Flat-Six",
    engineType: "Twin-Turbo",
    horsepower: 700,
    torqueNm: 750,
    zeroToHundred: 2.8,
    topSpeed: 340,
    drivetrain: "RWD",
    weightKg: 1470,
    perfCategory: "Super",
    categories: ["Supercars", "Track Cars", "European"],
    description: "With 700 horsepower sent only to the rear wheels, the GT2 RS is Porsche's most brutal and fastest 911 of its era.",
    query: "Porsche 911 GT2 RS 991",
    fallbackQuery: "Porsche 911 GT2 RS"
  },
  {
    id: "porsche-718-cayman-gt4-rs",
    brand: "Porsche",
    model: "718 Cayman GT4 RS",
    year: 2021,
    country: "Germany",
    bodyType: "Coupe",
    engine: "4.0L Naturally Aspirated Flat-Six (9A1 Evo)",
    engineType: "Naturally Aspirated",
    horsepower: 500,
    torqueNm: 450,
    zeroToHundred: 3.4,
    topSpeed: 315,
    drivetrain: "RWD",
    weightKg: 1415,
    perfCategory: "Super",
    categories: ["Track Cars", "European"],
    description: "Porsche dropped the 911 GT3's 9000-rpm engine into the mid-engined Cayman, creating a scalpel-sharp track weapon with 500 horsepower.",
    query: "Porsche 718 Cayman GT4 RS",
    fallbackQuery: "Porsche Cayman GT4 RS"
  },
  {
    id: "porsche-panamera-turbo-s",
    brand: "Porsche",
    model: "Panamera Turbo S",
    year: 2020,
    country: "Germany",
    bodyType: "Sedan",
    engine: "4.0L Twin-Turbo V8",
    engineType: "Twin-Turbo",
    horsepower: 630,
    torqueNm: 820,
    zeroToHundred: 3.1,
    topSpeed: 315,
    drivetrain: "AWD",
    weightKg: 2080,
    perfCategory: "Luxury",
    categories: ["Luxury", "European"],
    description: "The Panamera Turbo S hides 630 horsepower and a 315 km/h top speed beneath four doors and a genuinely opulent cabin.",
    query: "Porsche Panamera Turbo S",
    fallbackQuery: "Porsche Panamera Turbo S 971"
  },
  {
    id: "porsche-taycan-turbo-s",
    brand: "Porsche",
    model: "Taycan Turbo S",
    year: 2019,
    country: "Germany",
    bodyType: "Sedan",
    engine: "Dual Electric Motors (800V)",
    engineType: "Electric",
    horsepower: 761,
    torqueNm: 1050,
    zeroToHundred: 2.8,
    topSpeed: 260,
    drivetrain: "AWD",
    weightKg: 2295,
    perfCategory: "Super",
    categories: ["Electric", "Luxury", "European"],
    description: "Porsche's first electric car, the 800-volt Taycan Turbo S launched to 100 km/h in 2.8 seconds with repeatable, silent savagery.",
    query: "Porsche Taycan Turbo S",
    fallbackQuery: "Porsche Taycan"
  },
  {
    id: "ferrari-250-gto",
    brand: "Ferrari",
    model: "250 GTO",
    year: 1962,
    country: "Italy",
    bodyType: "Coupe",
    engine: "3.0L V12 (Tipo 168/62)",
    engineType: "Naturally Aspirated",
    horsepower: 300,
    torqueNm: 294,
    zeroToHundred: 6.1,
    topSpeed: 280,
    drivetrain: "RWD",
    weightKg: 1100,
    perfCategory: "Super",
    categories: ["Classic Cars", "Supercars"],
    description: "Only 36 were built, yet the 250 GTO's V12 and aerodynamic body made it the most valuable racing Ferrari in history.",
    query: "Ferrari 250 GTO",
    fallbackQuery: "Ferrari 250 GTO 1962"
  },
  {
    id: "ferrari-f40",
    brand: "Ferrari",
    model: "F40",
    year: 1987,
    country: "Italy",
    bodyType: "Coupe",
    engine: "2.9L Twin-Turbo V8 (F120A)",
    engineType: "Twin-Turbo",
    horsepower: 478,
    torqueNm: 577,
    zeroToHundred: 3.8,
    topSpeed: 324,
    drivetrain: "RWD",
    weightKg: 1100,
    perfCategory: "Hyper",
    categories: ["Supercars", "Classic Cars"],
    description: "Enzo Ferrari's final masterpiece, the F40 used twin turbos, Kevlar panels and zero driver aids to hit 324 km/h.",
    query: "Ferrari F40",
    fallbackQuery: "Ferrari F40 1987"
  },
  {
    id: "ferrari-f50",
    brand: "Ferrari",
    model: "F50",
    year: 1995,
    country: "Italy",
    bodyType: "Convertible",
    engine: "4.7L Naturally Aspirated V12 (F130)",
    engineType: "Naturally Aspirated",
    horsepower: 520,
    torqueNm: 471,
    zeroToHundred: 3.9,
    topSpeed: 325,
    drivetrain: "RWD",
    weightKg: 1230,
    perfCategory: "Hyper",
    categories: ["Supercars", "Classic Cars"],
    description: "The F50 bolted a Formula 1-derived V12 directly to a carbon tub, offering 520 naturally aspirated horsepower and no power steering.",
    query: "Ferrari F50",
    fallbackQuery: "Ferrari F50 1995"
  },
  {
    id: "ferrari-enzo",
    brand: "Ferrari",
    model: "Enzo",
    year: 2002,
    country: "Italy",
    bodyType: "Coupe",
    engine: "6.0L Naturally Aspirated V12 (F140B)",
    engineType: "Naturally Aspirated",
    horsepower: 660,
    torqueNm: 657,
    zeroToHundred: 3.65,
    topSpeed: 350,
    drivetrain: "RWD",
    weightKg: 1365,
    perfCategory: "Hyper",
    categories: ["Supercars"],
    description: "Named for the founder, the Enzo brought carbon-ceramic brakes and F1 paddle shifts to a 660-horsepower V12 road car.",
    query: "Ferrari Enzo",
    fallbackQuery: "Ferrari Enzo Ferrari"
  },
  {
    id: "ferrari-laferrari",
    brand: "Ferrari",
    model: "LaFerrari",
    year: 2013,
    country: "Italy",
    bodyType: "Coupe",
    engine: "6.3L V12 Hybrid (F140FE)",
    engineType: "Hybrid",
    horsepower: 963,
    torqueNm: 900,
    zeroToHundred: 2.6,
    topSpeed: 350,
    drivetrain: "RWD",
    weightKg: 1585,
    perfCategory: "Hyper",
    categories: ["Supercars", "Electric"],
    description: "The LaFerrari paired a 789-horsepower V12 with HY-KERS electric boost for 963 total horsepower and a sub-three-second sprint.",
    query: "Ferrari LaFerrari",
    fallbackQuery: "Ferrari LaFerrari 2013"
  },
  {
    id: "ferrari-458-italia",
    brand: "Ferrari",
    model: "458 Italia",
    year: 2009,
    country: "Italy",
    bodyType: "Coupe",
    engine: "4.5L Naturally Aspirated V8 (F136 FB)",
    engineType: "Naturally Aspirated",
    horsepower: 570,
    torqueNm: 540,
    zeroToHundred: 3.4,
    topSpeed: 325,
    drivetrain: "RWD",
    weightKg: 1485,
    perfCategory: "Super",
    categories: ["Supercars"],
    description: "The 458 Italia's 9000-rpm V8 and dual-clutch gearbox set a new benchmark for mid-engined Ferrari usability and sound.",
    query: "Ferrari 458 Italia",
    fallbackQuery: "Ferrari 458"
  },
  {
    id: "ferrari-812-superfast",
    brand: "Ferrari",
    model: "812 Superfast",
    year: 2017,
    country: "Italy",
    bodyType: "Coupe",
    engine: "6.5L Naturally Aspirated V12 (F140 GA)",
    engineType: "Naturally Aspirated",
    horsepower: 800,
    torqueNm: 718,
    zeroToHundred: 2.9,
    topSpeed: 340,
    drivetrain: "RWD",
    weightKg: 1630,
    perfCategory: "Super",
    categories: ["Supercars"],
    description: "The 812 Superfast revived the front-engined V12 berlinetta with 800 naturally aspirated horsepower and a 8900-rpm redline.",
    query: "Ferrari 812 Superfast",
    fallbackQuery: "Ferrari 812"
  },
  {
    id: "ferrari-sf90-stradale",
    brand: "Ferrari",
    model: "SF90 Stradale",
    year: 2019,
    country: "Italy",
    bodyType: "Coupe",
    engine: "4.0L Twin-Turbo V8 Hybrid (F154 FA)",
    engineType: "Hybrid",
    horsepower: 1000,
    torqueNm: 800,
    zeroToHundred: 2.5,
    topSpeed: 340,
    drivetrain: "AWD",
    weightKg: 1570,
    perfCategory: "Hyper",
    categories: ["Supercars", "Electric"],
    description: "Ferrari's first series-production plug-in hybrid, the SF90 Stradale summons 1000 horsepower from a V8 and three electric motors.",
    query: "Ferrari SF90 Stradale",
    fallbackQuery: "Ferrari SF90"
  },
  {
    id: "ferrari-296-gtb",
    brand: "Ferrari",
    model: "296 GTB",
    year: 2021,
    country: "Italy",
    bodyType: "Coupe",
    engine: "3.0L Twin-Turbo V6 Hybrid (F163)",
    engineType: "Hybrid",
    horsepower: 830,
    torqueNm: 740,
    zeroToHundred: 2.9,
    topSpeed: 330,
    drivetrain: "RWD",
    weightKg: 1470,
    perfCategory: "Super",
    categories: ["Supercars", "Electric"],
    description: "The 296 GTB revived Ferrari's mid-engined V6 lineage with a 120-degree twin-turbo unit and 830 hybrid-assisted horsepower.",
    query: "Ferrari 296 GTB",
    fallbackQuery: "Ferrari 296"
  }
];
