export default [
  // ---------------------------------------------------------------- Lamborghini
  {
    id: "lamborghini-miura",
    brand: "Lamborghini",
    model: "Miura P400",
    year: 1966,
    country: "Italy",
    bodyType: "Coupe",
    engine: "3.9L Naturally Aspirated V12",
    engineType: "Naturally Aspirated",
    horsepower: 350,
    torqueNm: 369,
    zeroToHundred: 6.7,
    topSpeed: 280,
    drivetrain: "RWD",
    weightKg: 1298,
    perfCategory: "Super",
    categories: ["Supercars", "European", "Classic Cars"],
    description: "The car that invented the mid-engined supercar, its transverse V12 and impossibly low body rewrote what a road car could look like overnight.",
    query: "Lamborghini Miura P400",
    fallbackQuery: "Lamborghini Miura",
  },
  {
    id: "lamborghini-countach",
    brand: "Lamborghini",
    model: "Countach LP400",
    year: 1974,
    country: "Italy",
    bodyType: "Coupe",
    engine: "3.9L Naturally Aspirated V12",
    engineType: "Naturally Aspirated",
    horsepower: 375,
    torqueNm: 361,
    zeroToHundred: 5.6,
    topSpeed: 309,
    drivetrain: "RWD",
    weightKg: 1065,
    perfCategory: "Super",
    categories: ["Supercars", "European", "Classic Cars"],
    description: "Marcello Gandini's razor-edged wedge defined the poster supercar, its scissor doors and periscope roof making every Countach an event before it moved.",
    query: "Lamborghini Countach LP400",
    fallbackQuery: "Lamborghini Countach",
  },
  {
    id: "lamborghini-diablo-sv",
    brand: "Lamborghini",
    model: "Diablo SV",
    year: 1995,
    country: "Italy",
    bodyType: "Coupe",
    engine: "5.7L Naturally Aspirated V12",
    engineType: "Naturally Aspirated",
    horsepower: 510,
    torqueNm: 580,
    zeroToHundred: 3.9,
    topSpeed: 328,
    drivetrain: "RWD",
    weightKg: 1576,
    perfCategory: "Super",
    categories: ["Supercars", "European", "Classic Cars"],
    description: "The rear-drive Diablo SV stripped away all-wheel grip for raw V12 theatre, its pop-up lights and huge wing a defiant analogue-era last stand.",
    query: "Lamborghini Diablo SV",
    fallbackQuery: "Lamborghini Diablo",
  },
  {
    id: "lamborghini-murcielago-sv",
    brand: "Lamborghini",
    model: "Murciélago LP670-4 SV",
    year: 2009,
    country: "Italy",
    bodyType: "Coupe",
    engine: "6.5L Naturally Aspirated V12",
    engineType: "Naturally Aspirated",
    horsepower: 670,
    torqueNm: 660,
    zeroToHundred: 3.2,
    topSpeed: 342,
    drivetrain: "AWD",
    weightKg: 1565,
    perfCategory: "Super",
    categories: ["Supercars", "European", "Track Cars"],
    description: "The final and fiercest Murciélago, the SuperVeloce shed weight and added a screaming 6.5-litre V12 for one last naturally aspirated hurrah.",
    query: "Lamborghini Murcielago LP670-4 SV",
    fallbackQuery: "Lamborghini Murcielago",
  },
  {
    id: "lamborghini-gallardo-superleggera",
    brand: "Lamborghini",
    model: "Gallardo LP570-4 Superleggera",
    year: 2010,
    country: "Italy",
    bodyType: "Coupe",
    engine: "5.2L Naturally Aspirated V10",
    engineType: "Naturally Aspirated",
    horsepower: 570,
    torqueNm: 540,
    zeroToHundred: 3.4,
    topSpeed: 325,
    drivetrain: "AWD",
    weightKg: 1340,
    perfCategory: "Super",
    categories: ["Supercars", "European", "Track Cars"],
    description: "Lamborghini's lightweight Gallardo swapped luxury for carbon fibre and Alcantara, its 5.2-litre V10 howling to 8,000 rpm with race-car urgency.",
    query: "Lamborghini Gallardo LP570-4 Superleggera",
    fallbackQuery: "Lamborghini Gallardo Superleggera",
  },
  {
    id: "lamborghini-aventador-svj",
    brand: "Lamborghini",
    model: "Aventador SVJ",
    year: 2018,
    country: "Italy",
    bodyType: "Coupe",
    engine: "6.5L Naturally Aspirated V12",
    engineType: "Naturally Aspirated",
    horsepower: 770,
    torqueNm: 720,
    zeroToHundred: 2.8,
    topSpeed: 350,
    drivetrain: "AWD",
    weightKg: 1525,
    perfCategory: "Hyper",
    categories: ["Supercars", "European", "Track Cars"],
    description: "Aerodynamic wizardry and a 770 hp V12 made the SVJ a Nürburgring record-breaker, its active ALA system bending air like a Le Mans prototype.",
    query: "Lamborghini Aventador SVJ",
    fallbackQuery: "Lamborghini Aventador",
  },
  {
    id: "lamborghini-huracan-sto",
    brand: "Lamborghini",
    model: "Huracán STO",
    year: 2020,
    country: "Italy",
    bodyType: "Coupe",
    engine: "5.2L Naturally Aspirated V10",
    engineType: "Naturally Aspirated",
    horsepower: 640,
    torqueNm: 565,
    zeroToHundred: 3.0,
    topSpeed: 310,
    drivetrain: "RWD",
    weightKg: 1339,
    perfCategory: "Super",
    categories: ["Supercars", "European", "Track Cars"],
    description: "A road-legal Super Trofeo racer, the STO wears a single-piece front clamshell and rear-drive V10 fury honed entirely for the circuit.",
    query: "Lamborghini Huracan STO",
    fallbackQuery: "Lamborghini Huracan",
  },
  {
    id: "lamborghini-urus",
    brand: "Lamborghini",
    model: "Urus",
    year: 2018,
    country: "Italy",
    bodyType: "SUV",
    engine: "4.0L Twin-Turbo V8",
    engineType: "Twin-Turbo",
    horsepower: 650,
    torqueNm: 850,
    zeroToHundred: 3.6,
    topSpeed: 305,
    drivetrain: "AWD",
    weightKg: 2200,
    perfCategory: "Super",
    categories: ["Supercars", "European", "Luxury"],
    description: "The super SUV that made 650 hp practical, the Urus pairs a twin-turbo V8 with Lamborghini drama and enough space for the whole family.",
    query: "Lamborghini Urus",
    fallbackQuery: "Lamborghini Urus SUV",
  },
  {
    id: "lamborghini-sian",
    brand: "Lamborghini",
    model: "Sián FKP 37",
    year: 2019,
    country: "Italy",
    bodyType: "Coupe",
    engine: "6.5L Naturally Aspirated V12 Hybrid",
    engineType: "Hybrid",
    horsepower: 819,
    torqueNm: 1050,
    zeroToHundred: 2.8,
    topSpeed: 350,
    drivetrain: "AWD",
    weightKg: 1620,
    perfCategory: "Hyper",
    categories: ["Supercars", "European", "Electric"],
    description: "Lamborghini's first hybrid supercar, the Sián uses a supercapacitor instead of batteries to feed its V12 for instant, lag-free electric boost.",
    query: "Lamborghini Sian FKP 37",
    fallbackQuery: "Lamborghini Sian",
  },

  // -------------------------------------------------------------------- McLaren
  {
    id: "mclaren-f1",
    brand: "McLaren",
    model: "F1",
    year: 1992,
    country: "United Kingdom",
    bodyType: "Coupe",
    engine: "6.1L Naturally Aspirated V12",
    engineType: "Naturally Aspirated",
    horsepower: 627,
    torqueNm: 651,
    zeroToHundred: 3.2,
    topSpeed: 386,
    drivetrain: "RWD",
    weightKg: 1138,
    perfCategory: "Hyper",
    categories: ["Supercars", "European", "Classic Cars"],
    description: "Gordon Murray's central-driving-seat masterpiece held the production speed record for a decade, its gold-lined V12 bay still a work of art.",
    query: "McLaren F1",
    fallbackQuery: "McLaren F1 road car",
  },
  {
    id: "mclaren-mp4-12c",
    brand: "McLaren",
    model: "MP4-12C",
    year: 2011,
    country: "United Kingdom",
    bodyType: "Coupe",
    engine: "3.8L Twin-Turbo V8",
    engineType: "Twin-Turbo",
    horsepower: 600,
    torqueNm: 600,
    zeroToHundred: 3.3,
    topSpeed: 330,
    drivetrain: "RWD",
    weightKg: 1434,
    perfCategory: "Super",
    categories: ["Supercars", "European"],
    description: "McLaren's modern rebirth arrived with a carbon tub and hydraulic suspension so clever it all but eliminated body roll on road and track alike.",
    query: "McLaren MP4-12C",
    fallbackQuery: "McLaren MP4 12C",
  },
  {
    id: "mclaren-p1",
    brand: "McLaren",
    model: "P1",
    year: 2013,
    country: "United Kingdom",
    bodyType: "Hypercar",
    engine: "3.8L Twin-Turbo V8 Hybrid",
    engineType: "Hybrid",
    horsepower: 916,
    torqueNm: 900,
    zeroToHundred: 2.8,
    topSpeed: 350,
    drivetrain: "RWD",
    weightKg: 1490,
    perfCategory: "Hyper",
    categories: ["Supercars", "European", "Electric"],
    description: "One third of the holy trinity, the P1 fused a twin-turbo V8 with electric torque fill and active aero to redefine the hypercar template.",
    query: "McLaren P1",
    fallbackQuery: "McLaren P1 hybrid",
  },
  {
    id: "mclaren-570s",
    brand: "McLaren",
    model: "570S",
    year: 2015,
    country: "United Kingdom",
    bodyType: "Coupe",
    engine: "3.8L Twin-Turbo V8",
    engineType: "Twin-Turbo",
    horsepower: 570,
    torqueNm: 600,
    zeroToHundred: 3.2,
    topSpeed: 328,
    drivetrain: "RWD",
    weightKg: 1313,
    perfCategory: "Super",
    categories: ["Supercars", "European"],
    description: "The Sports Series opened McLaren ownership to a wider audience, its carbon tub and 570 hp V8 delivering supercar pace with everyday usability.",
    query: "McLaren 570S",
    fallbackQuery: "McLaren 570S coupe",
  },
  {
    id: "mclaren-600lt",
    brand: "McLaren",
    model: "600LT",
    year: 2018,
    country: "United Kingdom",
    bodyType: "Coupe",
    engine: "3.8L Twin-Turbo V8",
    engineType: "Twin-Turbo",
    horsepower: 600,
    torqueNm: 620,
    zeroToHundred: 2.9,
    topSpeed: 328,
    drivetrain: "RWD",
    weightKg: 1247,
    perfCategory: "Super",
    categories: ["Supercars", "European", "Track Cars"],
    description: "The Longtail badge returned on the 600LT, its top-exit exhausts spitting flame as McLaren trimmed weight and sharpened every input for the track.",
    query: "McLaren 600LT",
    fallbackQuery: "McLaren 600 LT",
  },
  {
    id: "mclaren-765lt",
    brand: "McLaren",
    model: "765LT",
    year: 2020,
    country: "United Kingdom",
    bodyType: "Coupe",
    engine: "4.0L Twin-Turbo V8",
    engineType: "Twin-Turbo",
    horsepower: 765,
    torqueNm: 800,
    zeroToHundred: 2.8,
    topSpeed: 330,
    drivetrain: "RWD",
    weightKg: 1229,
    perfCategory: "Hyper",
    categories: ["Supercars", "European", "Track Cars"],
    description: "McLaren's most extreme Longtail yet, the 765LT drops 80 kg and adds power for a savagely quick, road-legal track weapon limited to 765 cars.",
    query: "McLaren 765LT",
    fallbackQuery: "McLaren 765 LT",
  },
  {
    id: "mclaren-senna",
    brand: "McLaren",
    model: "Senna",
    year: 2018,
    country: "United Kingdom",
    bodyType: "Hypercar",
    engine: "4.0L Twin-Turbo V8",
    engineType: "Twin-Turbo",
    horsepower: 800,
    torqueNm: 800,
    zeroToHundred: 2.8,
    topSpeed: 340,
    drivetrain: "RWD",
    weightKg: 1198,
    perfCategory: "Hyper",
    categories: ["Supercars", "European", "Track Cars"],
    description: "Named for Ayrton and built for lap times, the Senna's radical glass doors and enormous downforce make it a road-legal race car.",
    query: "McLaren Senna",
    fallbackQuery: "McLaren Senna supercar",
  },
  {
    id: "mclaren-speedtail",
    brand: "McLaren",
    model: "Speedtail",
    year: 2019,
    country: "United Kingdom",
    bodyType: "Coupe",
    engine: "4.0L Twin-Turbo V8 Hybrid",
    engineType: "Hybrid",
    horsepower: 1070,
    torqueNm: 1150,
    zeroToHundred: 2.9,
    topSpeed: 403,
    drivetrain: "RWD",
    weightKg: 1430,
    perfCategory: "Hyper",
    categories: ["Supercars", "European", "Electric"],
    description: "A three-seat spiritual successor to the F1, the Speedtail's teardrop body and 1,070 hp hybrid V8 push it past 400 km/h in serene comfort.",
    query: "McLaren Speedtail",
    fallbackQuery: "McLaren Speedtail hypercar",
  },
  {
    id: "mclaren-artura",
    brand: "McLaren",
    model: "Artura",
    year: 2022,
    country: "United Kingdom",
    bodyType: "Coupe",
    engine: "3.0L Twin-Turbo V6 Hybrid",
    engineType: "Hybrid",
    horsepower: 680,
    torqueNm: 720,
    zeroToHundred: 3.0,
    topSpeed: 330,
    drivetrain: "RWD",
    weightKg: 1498,
    perfCategory: "Super",
    categories: ["Supercars", "European", "Electric"],
    description: "McLaren's first series-production hybrid pairs a new twin-turbo V6 with an axial-flux motor, proving electrification need not blunt the driving thrill.",
    query: "McLaren Artura",
    fallbackQuery: "McLaren Artura hybrid",
  },

  // --------------------------------------------------------------- Aston Martin
  {
    id: "aston-martin-db5",
    brand: "Aston Martin",
    model: "DB5",
    year: 1963,
    country: "United Kingdom",
    bodyType: "Coupe",
    engine: "4.0L Naturally Aspirated Inline-6",
    engineType: "Naturally Aspirated",
    horsepower: 282,
    torqueNm: 380,
    zeroToHundred: 8.0,
    topSpeed: 233,
    drivetrain: "RWD",
    weightKg: 1465,
    perfCategory: "Sport",
    categories: ["European", "Classic Cars", "Luxury"],
    description: "The most famous car in cinema, the DB5's wire wheels and straight-six elegance made it the definitive British grand tourer of the sixties.",
    query: "Aston Martin DB5",
    fallbackQuery: "Aston Martin DB5 coupe",
  },
  {
    id: "aston-martin-db9",
    brand: "Aston Martin",
    model: "DB9",
    year: 2003,
    country: "United Kingdom",
    bodyType: "Coupe",
    engine: "5.9L Naturally Aspirated V12",
    engineType: "Naturally Aspirated",
    horsepower: 450,
    torqueNm: 570,
    zeroToHundred: 4.9,
    topSpeed: 300,
    drivetrain: "RWD",
    weightKg: 1710,
    perfCategory: "Sport",
    categories: ["European", "Luxury"],
    description: "The DB9 introduced Aston's bonded aluminium VH platform and a V12 soundtrack, its flowing lines ageing into one of the era's most graceful shapes.",
    query: "Aston Martin DB9",
    fallbackQuery: "Aston Martin DB9 coupe",
  },
  {
    id: "aston-martin-vantage",
    brand: "Aston Martin",
    model: "Vantage",
    year: 2018,
    country: "United Kingdom",
    bodyType: "Coupe",
    engine: "4.0L Twin-Turbo V8",
    engineType: "Twin-Turbo",
    horsepower: 510,
    torqueNm: 685,
    zeroToHundred: 3.6,
    topSpeed: 314,
    drivetrain: "RWD",
    weightKg: 1530,
    perfCategory: "Super",
    categories: ["Supercars", "European", "Track Cars"],
    description: "The sharpest Vantage yet, its Mercedes-sourced twin-turbo V8 and muscular haunches giving Aston a genuine sports car edge.",
    query: "Aston Martin Vantage 2018",
    fallbackQuery: "Aston Martin Vantage",
  },
  {
    id: "aston-martin-db11",
    brand: "Aston Martin",
    model: "DB11",
    year: 2016,
    country: "United Kingdom",
    bodyType: "Coupe",
    engine: "5.2L Twin-Turbo V12",
    engineType: "Twin-Turbo",
    horsepower: 608,
    torqueNm: 700,
    zeroToHundred: 3.9,
    topSpeed: 322,
    drivetrain: "RWD",
    weightKg: 1770,
    perfCategory: "Super",
    categories: ["Supercars", "European", "Luxury"],
    description: "The DB11 launched Aston's new design language with a clamshell bonnet and aero-blade details, its in-house twin-turbo V12 a proper grand tourer heart.",
    query: "Aston Martin DB11",
    fallbackQuery: "Aston Martin DB11 coupe",
  },
  {
    id: "aston-martin-db12",
    brand: "Aston Martin",
    model: "DB12",
    year: 2023,
    country: "United Kingdom",
    bodyType: "Coupe",
    engine: "4.0L Twin-Turbo V8",
    engineType: "Twin-Turbo",
    horsepower: 680,
    torqueNm: 800,
    zeroToHundred: 3.6,
    topSpeed: 325,
    drivetrain: "RWD",
    weightKg: 1685,
    perfCategory: "Super",
    categories: ["Supercars", "European", "Luxury"],
    description: "Billed as the world's first super tourer, the DB12 sharpens the DB11 formula with more power, a redesigned cabin and genuine dynamic bite.",
    query: "Aston Martin DB12",
    fallbackQuery: "Aston Martin DB12 coupe",
  },
  {
    id: "aston-martin-vanquish",
    brand: "Aston Martin",
    model: "Vanquish",
    year: 2012,
    country: "United Kingdom",
    bodyType: "Coupe",
    engine: "5.9L Naturally Aspirated V12",
    engineType: "Naturally Aspirated",
    horsepower: 573,
    torqueNm: 620,
    zeroToHundred: 4.1,
    topSpeed: 295,
    drivetrain: "RWD",
    weightKg: 1739,
    perfCategory: "Super",
    categories: ["Supercars", "European", "Luxury"],
    description: "The second-generation Vanquish crowned Aston's range with a carbon-bodied flagship, its 573 hp V12 and eight-speed auto blending speed with opulence.",
    query: "Aston Martin Vanquish 2012",
    fallbackQuery: "Aston Martin Vanquish",
  },
  {
    id: "aston-martin-rapide",
    brand: "Aston Martin",
    model: "Rapide",
    year: 2010,
    country: "United Kingdom",
    bodyType: "Sedan",
    engine: "5.9L Naturally Aspirated V12",
    engineType: "Naturally Aspirated",
    horsepower: 470,
    torqueNm: 600,
    zeroToHundred: 5.3,
    topSpeed: 296,
    drivetrain: "RWD",
    weightKg: 1950,
    perfCategory: "Luxury",
    categories: ["European", "Luxury"],
    description: "Aston's four-door gamble, the Rapide stretched the DB9's V12 elegance into a sleek saloon that promised supercar drama with room for four.",
    query: "Aston Martin Rapide",
    fallbackQuery: "Aston Martin Rapide sedan",
  },
  {
    id: "aston-martin-valkyrie",
    brand: "Aston Martin",
    model: "Valkyrie",
    year: 2021,
    country: "United Kingdom",
    bodyType: "Hypercar",
    engine: "6.5L Naturally Aspirated V12 Hybrid",
    engineType: "Hybrid",
    horsepower: 1160,
    torqueNm: 900,
    zeroToHundred: 2.5,
    topSpeed: 350,
    drivetrain: "RWD",
    weightKg: 1030,
    perfCategory: "Hyper",
    categories: ["Supercars", "European", "Track Cars"],
    description: "Co-developed with Red Bull, the Valkyrie is a Formula One car for the road, its Cosworth V12 revving to 11,100 rpm in a carbon monocoque.",
    query: "Aston Martin Valkyrie",
    fallbackQuery: "Aston Martin Valkyrie hypercar",
  },
  {
    id: "aston-martin-valhalla",
    brand: "Aston Martin",
    model: "Valhalla",
    year: 2023,
    country: "United Kingdom",
    bodyType: "Hypercar",
    engine: "4.0L Twin-Turbo V8 Hybrid",
    engineType: "Hybrid",
    horsepower: 1064,
    torqueNm: 1100,
    zeroToHundred: 2.5,
    topSpeed: 350,
    drivetrain: "AWD",
    weightKg: 1655,
    perfCategory: "Hyper",
    categories: ["Supercars", "European", "Electric"],
    description: "The Valhalla brings Valkyrie thinking to a usable supercar, a flat-plane twin-turbo V8 and three motors driving all four wheels.",
    query: "Aston Martin Valhalla",
    fallbackQuery: "Aston Martin Valhalla hybrid",
  },

  // ---------------------------------------------------------------- Rolls-Royce
  {
    id: "rolls-royce-silver-shadow",
    brand: "Rolls-Royce",
    model: "Silver Shadow",
    year: 1965,
    country: "United Kingdom",
    bodyType: "Sedan",
    engine: "6.2L Naturally Aspirated V8",
    engineType: "Naturally Aspirated",
    horsepower: 200,
    torqueNm: 400,
    zeroToHundred: 10.5,
    topSpeed: 185,
    drivetrain: "RWD",
    weightKg: 2108,
    perfCategory: "Luxury",
    categories: ["European", "Luxury", "Classic Cars"],
    description: "The Silver Shadow modernised Rolls-Royce with unitary construction and self-levelling suspension, becoming the marque's most-produced model ever.",
    query: "Rolls-Royce Silver Shadow",
    fallbackQuery: "Rolls Royce Silver Shadow",
  },
  {
    id: "rolls-royce-corniche",
    brand: "Rolls-Royce",
    model: "Corniche",
    year: 1971,
    country: "United Kingdom",
    bodyType: "Convertible",
    engine: "6.75L Naturally Aspirated V8",
    engineType: "Naturally Aspirated",
    horsepower: 220,
    torqueNm: 450,
    zeroToHundred: 9.6,
    topSpeed: 190,
    drivetrain: "RWD",
    weightKg: 2200,
    perfCategory: "Luxury",
    categories: ["European", "Luxury", "Classic Cars"],
    description: "The Corniche was Rolls-Royce's coachbuilt flagship, a two-door convertible so costly it outlasted three decades of changing tastes.",
    query: "Rolls-Royce Corniche",
    fallbackQuery: "Rolls Royce Corniche convertible",
  },
  {
    id: "rolls-royce-silver-spur",
    brand: "Rolls-Royce",
    model: "Silver Spur",
    year: 1980,
    country: "United Kingdom",
    bodyType: "Sedan",
    engine: "6.75L Naturally Aspirated V8",
    engineType: "Naturally Aspirated",
    horsepower: 220,
    torqueNm: 450,
    zeroToHundred: 9.8,
    topSpeed: 200,
    drivetrain: "RWD",
    weightKg: 2300,
    perfCategory: "Luxury",
    categories: ["European", "Luxury", "Classic Cars"],
    description: "The long-wheelbase Silver Spur added rear legroom and presence to the Shadow line, its 6.75-litre V8 wafting along with barely a whisper.",
    query: "Rolls-Royce Silver Spur",
    fallbackQuery: "Rolls Royce Silver Spur",
  },
  {
    id: "rolls-royce-phantom-coupe",
    brand: "Rolls-Royce",
    model: "Phantom Coupé",
    year: 2008,
    country: "United Kingdom",
    bodyType: "Coupe",
    engine: "6.75L Naturally Aspirated V12",
    engineType: "Naturally Aspirated",
    horsepower: 453,
    torqueNm: 720,
    zeroToHundred: 5.8,
    topSpeed: 250,
    drivetrain: "RWD",
    weightKg: 2590,
    perfCategory: "Luxury",
    categories: ["European", "Luxury"],
    description: "The Phantom Coupé turned Rolls-Royce's flagship into a two-door statement, its brushed steel bonnet and coach doors pure bespoke theatre.",
    query: "Rolls-Royce Phantom Coupe",
    fallbackQuery: "Rolls Royce Phantom Coupe",
  },
  {
    id: "rolls-royce-ghost",
    brand: "Rolls-Royce",
    model: "Ghost",
    year: 2010,
    country: "United Kingdom",
    bodyType: "Sedan",
    engine: "6.6L Twin-Turbo V12",
    engineType: "Twin-Turbo",
    horsepower: 563,
    torqueNm: 780,
    zeroToHundred: 4.9,
    topSpeed: 250,
    drivetrain: "RWD",
    weightKg: 2435,
    perfCategory: "Luxury",
    categories: ["European", "Luxury"],
    description: "The Ghost made Rolls-Royce relevant to owner-drivers, its twin-turbo V12 and magic-carpet ride wrapped in understated, contemporary luxury.",
    query: "Rolls-Royce Ghost 2010",
    fallbackQuery: "Rolls Royce Ghost",
  },
  {
    id: "rolls-royce-wraith",
    brand: "Rolls-Royce",
    model: "Wraith",
    year: 2013,
    country: "United Kingdom",
    bodyType: "Coupe",
    engine: "6.6L Twin-Turbo V12",
    engineType: "Twin-Turbo",
    horsepower: 624,
    torqueNm: 800,
    zeroToHundred: 4.6,
    topSpeed: 250,
    drivetrain: "RWD",
    weightKg: 2440,
    perfCategory: "Luxury",
    categories: ["European", "Luxury"],
    description: "The most powerful Rolls-Royce of its day, the Wraith's fastback roofline and 624 hp V12 made it the marque's grandest grand tourer.",
    query: "Rolls-Royce Wraith",
    fallbackQuery: "Rolls Royce Wraith coupe",
  },
  {
    id: "rolls-royce-dawn",
    brand: "Rolls-Royce",
    model: "Dawn",
    year: 2015,
    country: "United Kingdom",
    bodyType: "Convertible",
    engine: "6.6L Twin-Turbo V12",
    engineType: "Twin-Turbo",
    horsepower: 563,
    torqueNm: 780,
    zeroToHundred: 5.0,
    topSpeed: 250,
    drivetrain: "RWD",
    weightKg: 2560,
    perfCategory: "Luxury",
    categories: ["European", "Luxury"],
    description: "The Dawn is the Wraith's drop-top twin, a silent six-layer roof and 563 hp V12 delivering open-air opulence at any speed you care to name.",
    query: "Rolls-Royce Dawn",
    fallbackQuery: "Rolls Royce Dawn convertible",
  },
  {
    id: "rolls-royce-cullinan",
    brand: "Rolls-Royce",
    model: "Cullinan",
    year: 2018,
    country: "United Kingdom",
    bodyType: "SUV",
    engine: "6.75L Twin-Turbo V12",
    engineType: "Twin-Turbo",
    horsepower: 563,
    torqueNm: 850,
    zeroToHundred: 5.2,
    topSpeed: 250,
    drivetrain: "AWD",
    weightKg: 2660,
    perfCategory: "Luxury",
    categories: ["European", "Luxury"],
    description: "Rolls-Royce's first SUV, the Cullinan brings magic-carpet comfort and a 6.75-litre V12 to any terrain, with a rear tailgate for the opera set.",
    query: "Rolls-Royce Cullinan",
    fallbackQuery: "Rolls Royce Cullinan SUV",
  },
  {
    id: "rolls-royce-spectre",
    brand: "Rolls-Royce",
    model: "Spectre",
    year: 2023,
    country: "United Kingdom",
    bodyType: "Coupe",
    engine: "Dual Electric Motor",
    engineType: "Electric",
    horsepower: 577,
    torqueNm: 900,
    zeroToHundred: 4.5,
    topSpeed: 250,
    drivetrain: "AWD",
    weightKg: 2890,
    perfCategory: "Luxury",
    categories: ["European", "Luxury", "Electric"],
    description: "The Spectre is Rolls-Royce's first electric car, a silent 577 hp coupe whose 102 kWh battery glides the marque into a hushed new era.",
    query: "Rolls-Royce Spectre",
    fallbackQuery: "Rolls Royce Spectre electric",
  },
];
