export default [
  {
    id: "bmw-m1",
    brand: "BMW",
    model: "M1",
    year: 1978,
    country: "Germany",
    bodyType: "Coupe",
    engine: "3.5L Inline-Six (M88)",
    engineType: "Naturally Aspirated",
    horsepower: 277,
    torqueNm: 330,
    zeroToHundred: 5.6,
    topSpeed: 262,
    drivetrain: "RWD",
    weightKg: 1300,
    perfCategory: "Super",
    categories: ["European", "Classic Cars"],
    description: "BMW's only mid-engined supercar, the Giugiaro-styled M1 paired a screaming M88 straight-six with race-bred balance and genuine 260 km/h pace.",
    query: "BMW M1 (E26)",
    fallbackQuery: "BMW M1"
  },
  {
    id: "bmw-1m-coupe",
    brand: "BMW",
    model: "1 Series M Coupe",
    year: 2011,
    country: "Germany",
    bodyType: "Coupe",
    engine: "3.0L Twin-Turbo Inline-Six (N54)",
    engineType: "Twin-Turbo",
    horsepower: 340,
    torqueNm: 500,
    zeroToHundred: 4.9,
    topSpeed: 250,
    drivetrain: "RWD",
    weightKg: 1495,
    perfCategory: "Sport",
    categories: ["European", "Track Cars"],
    description: "The compact 1M Coupe squeezed the M3's twin-turbo straight-six into a short wheelbase, delivering raw rear-drive thrills in a limited run.",
    query: "BMW 1 Series M Coupe",
    fallbackQuery: "BMW 1M"
  },
  {
    id: "bmw-m2-g87",
    brand: "BMW",
    model: "M2 (G87)",
    year: 2023,
    country: "Germany",
    bodyType: "Coupe",
    engine: "3.0L Twin-Turbo Inline-Six (S58)",
    engineType: "Twin-Turbo",
    horsepower: 460,
    torqueNm: 550,
    zeroToHundred: 4.1,
    topSpeed: 250,
    drivetrain: "RWD",
    weightKg: 1725,
    perfCategory: "Sport",
    categories: ["European", "Track Cars"],
    description: "The G87 M2 keeps the classic recipe alive with a punchy S58 straight-six, rear-wheel drive and boxy flared arches that echo the original.",
    query: "BMW M2 (G87)",
    fallbackQuery: "BMW M2"
  },
  {
    id: "bmw-m4-g82",
    brand: "BMW",
    model: "M4 Competition (G82)",
    year: 2021,
    country: "Germany",
    bodyType: "Coupe",
    engine: "3.0L Twin-Turbo Inline-Six (S58)",
    engineType: "Twin-Turbo",
    horsepower: 510,
    torqueNm: 650,
    zeroToHundred: 3.9,
    topSpeed: 250,
    drivetrain: "RWD",
    weightKg: 1725,
    perfCategory: "Sport",
    categories: ["European", "Track Cars"],
    description: "The G82 M4 Competition brought a controversial tall grille and a 510 hp S58 straight-six, blending track pace with everyday usability.",
    query: "BMW M4 (G82)",
    fallbackQuery: "BMW M4 Competition"
  },
  {
    id: "bmw-m5-f90",
    brand: "BMW",
    model: "M5 (F90)",
    year: 2018,
    country: "Germany",
    bodyType: "Sedan",
    engine: "4.4L Twin-Turbo V8 (S63)",
    engineType: "Twin-Turbo",
    horsepower: 600,
    torqueNm: 750,
    zeroToHundred: 3.4,
    topSpeed: 305,
    drivetrain: "AWD",
    weightKg: 1930,
    perfCategory: "Sport",
    categories: ["European", "Track Cars"],
    description: "The F90 M5 introduced switchable M xDrive to the super-sedan formula, letting 600 hp reach all four wheels or just the rear.",
    query: "BMW M5 (F90)",
    fallbackQuery: "BMW M5"
  },
  {
    id: "bmw-m6-gran-coupe-f06",
    brand: "BMW",
    model: "M6 Gran Coupe (F06)",
    year: 2013,
    country: "Germany",
    bodyType: "Sedan",
    engine: "4.4L Twin-Turbo V8 (S63)",
    engineType: "Twin-Turbo",
    horsepower: 560,
    torqueNm: 680,
    zeroToHundred: 4.2,
    topSpeed: 305,
    drivetrain: "RWD",
    weightKg: 1975,
    perfCategory: "Luxury",
    categories: ["European", "Luxury"],
    description: "The four-door M6 Gran Coupe wrapped the M5's twin-turbo V8 in a sleek fastback body, mixing grand-touring elegance with serious pace.",
    query: "BMW M6 Gran Coupe (F06)",
    fallbackQuery: "BMW M6 Gran Coupe"
  },
  {
    id: "bmw-m8-competition-f92",
    brand: "BMW",
    model: "M8 Competition (F92)",
    year: 2019,
    country: "Germany",
    bodyType: "Coupe",
    engine: "4.4L Twin-Turbo V8 (S63)",
    engineType: "Twin-Turbo",
    horsepower: 625,
    torqueNm: 750,
    zeroToHundred: 3.2,
    topSpeed: 305,
    drivetrain: "AWD",
    weightKg: 1960,
    perfCategory: "Super",
    categories: ["European", "Luxury"],
    description: "The M8 Competition is BMW's flagship grand tourer, its 625 hp twin-turbo V8 and M xDrive delivering supercar pace in a plush coupe.",
    query: "BMW M8 Competition (F92)",
    fallbackQuery: "BMW M8"
  },
  {
    id: "bmw-m3-e30",
    brand: "BMW",
    model: "M3 (E30)",
    year: 1986,
    country: "Germany",
    bodyType: "Coupe",
    engine: "2.3L Inline-Four (S14)",
    engineType: "Naturally Aspirated",
    horsepower: 200,
    torqueNm: 240,
    zeroToHundred: 6.7,
    topSpeed: 235,
    drivetrain: "RWD",
    weightKg: 1200,
    perfCategory: "Sport",
    categories: ["European", "Classic Cars", "Track Cars"],
    description: "The boxy E30 M3 homologation special turned BMW's compact coupe into a touring-car legend with its high-revving S14 four and flared body.",
    query: "BMW M3 (E30)",
    fallbackQuery: "BMW M3 E30"
  },
  {
    id: "bmw-330i-g20",
    brand: "BMW",
    model: "330i (G20)",
    year: 2019,
    country: "Germany",
    bodyType: "Sedan",
    engine: "2.0L Turbo Inline-Four (B48)",
    engineType: "Turbo",
    horsepower: 258,
    torqueNm: 400,
    zeroToHundred: 5.5,
    topSpeed: 250,
    drivetrain: "RWD",
    weightKg: 1619,
    perfCategory: "Luxury",
    categories: ["European", "Luxury"],
    description: "The G20 330i is the sweet spot of the modern 3 Series, its 258 hp turbo four and sharp chassis balancing comfort with driver reward.",
    query: "BMW 330i (G20)",
    fallbackQuery: "BMW 3 Series G20"
  },
  {
    id: "bmw-320i-g20",
    brand: "BMW",
    model: "320i (G20)",
    year: 2019,
    country: "Germany",
    bodyType: "Sedan",
    engine: "2.0L Turbo Inline-Four (B48)",
    engineType: "Turbo",
    horsepower: 184,
    torqueNm: 300,
    zeroToHundred: 7.1,
    topSpeed: 240,
    drivetrain: "RWD",
    weightKg: 1545,
    perfCategory: "Luxury",
    categories: ["European", "Luxury"],
    description: "The entry-level G20 320i offers the same polished chassis as its siblings with a frugal 184 hp turbo four for everyday driving.",
    query: "BMW 320i (G20)",
    fallbackQuery: "BMW 3 Series G20"
  },
  {
    id: "mercedes-300sl-gullwing",
    brand: "Mercedes-Benz",
    model: "300 SL Gullwing (W198)",
    year: 1955,
    country: "Germany",
    bodyType: "Coupe",
    engine: "3.0L Inline-Six (M198)",
    engineType: "Naturally Aspirated",
    horsepower: 215,
    torqueNm: 275,
    zeroToHundred: 8.8,
    topSpeed: 260,
    drivetrain: "RWD",
    weightKg: 1295,
    perfCategory: "Luxury",
    categories: ["European", "Classic Cars", "Luxury"],
    description: "The 300 SL Gullwing stunned 1950s crowds with its spaceframe chassis, fuel-injected straight-six and the most famous doors in motoring.",
    query: "Mercedes-Benz 300 SL Gullwing",
    fallbackQuery: "Mercedes-Benz 300 SL"
  },
  {
    id: "mercedes-190e-evo2",
    brand: "Mercedes-Benz",
    model: "190E 2.5-16 Evolution II",
    year: 1990,
    country: "Germany",
    bodyType: "Sedan",
    engine: "2.5L Inline-Four (M102)",
    engineType: "Naturally Aspirated",
    horsepower: 235,
    torqueNm: 245,
    zeroToHundred: 7.1,
    topSpeed: 250,
    drivetrain: "RWD",
    weightKg: 1340,
    perfCategory: "Sport",
    categories: ["European", "Classic Cars", "Track Cars"],
    description: "Built to homologate Mercedes for the DTM, the wild-winged Evolution II is the most extreme road-going 190E ever produced.",
    query: "Mercedes-Benz 190E 2.5-16 Evolution II",
    fallbackQuery: "Mercedes-Benz 190E Evolution"
  },
  {
    id: "mercedes-clk-gtr",
    brand: "Mercedes-Benz",
    model: "CLK GTR",
    year: 1997,
    country: "Germany",
    bodyType: "Coupe",
    engine: "6.9L V12 (M120)",
    engineType: "Naturally Aspirated",
    horsepower: 612,
    torqueNm: 775,
    zeroToHundred: 3.8,
    topSpeed: 344,
    drivetrain: "RWD",
    weightKg: 1440,
    perfCategory: "Hyper",
    categories: ["European", "Track Cars", "Classic Cars"],
    description: "A race car with number plates, the CLK GTR packed a mid-mounted 6.9-litre V12 and dominated GT racing before hitting the road.",
    query: "Mercedes-Benz CLK GTR",
    fallbackQuery: "Mercedes CLK GTR"
  },
  {
    id: "mercedes-slr-mclaren",
    brand: "Mercedes-Benz",
    model: "SLR McLaren",
    year: 2003,
    country: "Germany",
    bodyType: "Coupe",
    engine: "5.4L Supercharged V8 (M155)",
    engineType: "Supercharged",
    horsepower: 617,
    torqueNm: 780,
    zeroToHundred: 3.8,
    topSpeed: 334,
    drivetrain: "RWD",
    weightKg: 1768,
    perfCategory: "Super",
    categories: ["European", "Luxury"],
    description: "The SLR McLaren fused Mercedes grand-touring comfort with McLaren carbon-fibre engineering and a thunderous supercharged V8.",
    query: "Mercedes-Benz SLR McLaren",
    fallbackQuery: "Mercedes SLR McLaren"
  },
  {
    id: "mercedes-sls-amg",
    brand: "Mercedes-Benz",
    model: "SLS AMG",
    year: 2010,
    country: "Germany",
    bodyType: "Coupe",
    engine: "6.2L V8 (M159)",
    engineType: "Naturally Aspirated",
    horsepower: 571,
    torqueNm: 650,
    zeroToHundred: 3.8,
    topSpeed: 317,
    drivetrain: "RWD",
    weightKg: 1620,
    perfCategory: "Super",
    categories: ["European", "Luxury"],
    description: "The SLS AMG revived the gullwing door and paired it with a naturally aspirated 6.2-litre V8, a front-mid layout and a glorious soundtrack.",
    query: "Mercedes-Benz SLS AMG",
    fallbackQuery: "Mercedes SLS AMG"
  },
  {
    id: "mercedes-c63-amg-w204",
    brand: "Mercedes-Benz",
    model: "C63 AMG (W204)",
    year: 2011,
    country: "Germany",
    bodyType: "Sedan",
    engine: "6.2L V8 (M156)",
    engineType: "Naturally Aspirated",
    horsepower: 457,
    torqueNm: 600,
    zeroToHundred: 4.5,
    topSpeed: 250,
    drivetrain: "RWD",
    weightKg: 1730,
    perfCategory: "Sport",
    categories: ["European", "Muscle"],
    description: "The W204 C63 AMG stuffed a naturally aspirated 6.2-litre V8 into a compact saloon, creating a tyre-shredding modern muscle car.",
    query: "Mercedes-Benz C63 AMG (W204)",
    fallbackQuery: "Mercedes C63 AMG W204"
  },
  {
    id: "mercedes-e63-amg-w213",
    brand: "Mercedes-Benz",
    model: "E63 AMG (W213)",
    year: 2017,
    country: "Germany",
    bodyType: "Sedan",
    engine: "4.0L Twin-Turbo V8 (M177)",
    engineType: "Twin-Turbo",
    horsepower: 612,
    torqueNm: 850,
    zeroToHundred: 3.4,
    topSpeed: 300,
    drivetrain: "AWD",
    weightKg: 1950,
    perfCategory: "Sport",
    categories: ["European", "Luxury"],
    description: "The W213 E63 S combined a 612 hp twin-turbo V8 with fully variable 4MATIC+ all-wheel drive, making it a devastating all-weather express.",
    query: "Mercedes-AMG E63 (W213)",
    fallbackQuery: "Mercedes E63 AMG"
  },
  {
    id: "mercedes-g63-amg-w463",
    brand: "Mercedes-Benz",
    model: "G63 AMG (W463)",
    year: 2019,
    country: "Germany",
    bodyType: "SUV",
    engine: "4.0L Twin-Turbo V8 (M177)",
    engineType: "Twin-Turbo",
    horsepower: 585,
    torqueNm: 850,
    zeroToHundred: 4.5,
    topSpeed: 220,
    drivetrain: "AWD",
    weightKg: 2560,
    perfCategory: "Luxury",
    categories: ["European", "Luxury"],
    description: "The G63 AMG turns the boxy Geländewagen into a 585 hp luxury brute, its twin-turbo V8 and three locking diffs defying physics.",
    query: "Mercedes-AMG G63 (W463)",
    fallbackQuery: "Mercedes G63 AMG"
  },
  {
    id: "mercedes-s63-amg-w222",
    brand: "Mercedes-Benz",
    model: "S63 AMG (W222)",
    year: 2014,
    country: "Germany",
    bodyType: "Sedan",
    engine: "5.5L Twin-Turbo V8 (M157)",
    engineType: "Twin-Turbo",
    horsepower: 585,
    torqueNm: 900,
    zeroToHundred: 4.4,
    topSpeed: 250,
    drivetrain: "RWD",
    weightKg: 1955,
    perfCategory: "Luxury",
    categories: ["European", "Luxury"],
    description: "The W222 S63 AMG blends first-class luxury with a 900 Nm twin-turbo V8, proving a flagship limousine can still terrify its passengers.",
    query: "Mercedes-Benz S63 AMG (W222)",
    fallbackQuery: "Mercedes S63 AMG"
  },
  {
    id: "audi-quattro-ur",
    brand: "Audi",
    model: "Quattro (Ur-Quattro)",
    year: 1980,
    country: "Germany",
    bodyType: "Coupe",
    engine: "2.1L Turbo Inline-Five",
    engineType: "Turbo",
    horsepower: 200,
    torqueNm: 285,
    zeroToHundred: 6.7,
    topSpeed: 220,
    drivetrain: "quattro AWD",
    weightKg: 1290,
    perfCategory: "Sport",
    categories: ["European", "Classic Cars"],
    description: "The Ur-Quattro introduced permanent all-wheel drive to rallying and the road, its turbocharged five-cylinder rewriting the rulebook.",
    query: "Audi Quattro (Ur-Quattro)",
    fallbackQuery: "Audi Quattro"
  },
  {
    id: "audi-rs2-avant",
    brand: "Audi",
    model: "RS2 Avant",
    year: 1994,
    country: "Germany",
    bodyType: "Wagon",
    engine: "2.2L Turbo Inline-Five (ADU)",
    engineType: "Turbo",
    horsepower: 315,
    torqueNm: 410,
    zeroToHundred: 5.4,
    topSpeed: 262,
    drivetrain: "quattro AWD",
    weightKg: 1595,
    perfCategory: "Sport",
    categories: ["European", "Classic Cars"],
    description: "Co-developed with Porsche, the RS2 Avant invented the fast estate with a 315 hp five-cylinder and genuine supercar-humbling pace.",
    query: "Audi RS2 Avant",
    fallbackQuery: "Audi RS2"
  },
  {
    id: "audi-rs3-8y",
    brand: "Audi",
    model: "RS3 Sportback (8Y)",
    year: 2021,
    country: "Germany",
    bodyType: "Hatchback",
    engine: "2.5L Turbo Inline-Five (DAZA)",
    engineType: "Turbo",
    horsepower: 400,
    torqueNm: 500,
    zeroToHundred: 3.8,
    topSpeed: 250,
    drivetrain: "quattro AWD",
    weightKg: 1656,
    perfCategory: "Sport",
    categories: ["European", "Track Cars"],
    description: "The 8Y RS3 Sportback pairs its iconic 400 hp five-cylinder with a torque-vectoring rear diff, making it a giant-killing hot hatch.",
    query: "Audi RS3 Sportback (8Y)",
    fallbackQuery: "Audi RS3"
  },
  {
    id: "audi-rs5-b9",
    brand: "Audi",
    model: "RS5 Coupe (B9)",
    year: 2017,
    country: "Germany",
    bodyType: "Coupe",
    engine: "2.9L Twin-Turbo V6 (EA839)",
    engineType: "Twin-Turbo",
    horsepower: 450,
    torqueNm: 600,
    zeroToHundred: 3.9,
    topSpeed: 250,
    drivetrain: "quattro AWD",
    weightKg: 1695,
    perfCategory: "Sport",
    categories: ["European", "Track Cars"],
    description: "The B9 RS5 swapped its predecessor's V8 for a lighter twin-turbo V6, sharpening the coupe into a precise all-weather performance machine.",
    query: "Audi RS5 Coupe (B9)",
    fallbackQuery: "Audi RS5"
  },
  {
    id: "audi-rs6-c8",
    brand: "Audi",
    model: "RS6 Avant (C8)",
    year: 2019,
    country: "Germany",
    bodyType: "Wagon",
    engine: "4.0L Twin-Turbo V8 (EA825)",
    engineType: "Twin-Turbo",
    horsepower: 600,
    torqueNm: 800,
    zeroToHundred: 3.6,
    topSpeed: 250,
    drivetrain: "quattro AWD",
    weightKg: 2075,
    perfCategory: "Super",
    categories: ["European", "Track Cars"],
    description: "The C8 RS6 Avant is the definitive super-estate, its 600 hp twin-turbo V8 and wide arches delivering supercar pace with family practicality.",
    query: "Audi RS6 Avant (C8)",
    fallbackQuery: "Audi RS6 Avant"
  },
  {
    id: "audi-rs7-c8",
    brand: "Audi",
    model: "RS7 Sportback (C8)",
    year: 2019,
    country: "Germany",
    bodyType: "Hatchback",
    engine: "4.0L Twin-Turbo V8 (EA825)",
    engineType: "Twin-Turbo",
    horsepower: 600,
    torqueNm: 800,
    zeroToHundred: 3.6,
    topSpeed: 250,
    drivetrain: "quattro AWD",
    weightKg: 2140,
    perfCategory: "Super",
    categories: ["European", "Luxury"],
    description: "The C8 RS7 Sportback cloaks the RS6's 600 hp twin-turbo V8 in a sleek four-door coupe body, blending brutal pace with executive style.",
    query: "Audi RS7 Sportback (C8)",
    fallbackQuery: "Audi RS7"
  },
  {
    id: "audi-tt-rs-8s",
    brand: "Audi",
    model: "TT RS (8S)",
    year: 2016,
    country: "Germany",
    bodyType: "Coupe",
    engine: "2.5L Turbo Inline-Five (DAZA)",
    engineType: "Turbo",
    horsepower: 400,
    torqueNm: 480,
    zeroToHundred: 3.7,
    topSpeed: 250,
    drivetrain: "quattro AWD",
    weightKg: 1475,
    perfCategory: "Sport",
    categories: ["European", "Track Cars"],
    description: "The 8S TT RS packs Audi's celebrated 400 hp five-cylinder into a compact coupe, offering supercar acceleration in a nimble package.",
    query: "Audi TT RS (8S)",
    fallbackQuery: "Audi TT RS"
  },
  {
    id: "audi-s4-b9",
    brand: "Audi",
    model: "S4 (B9)",
    year: 2016,
    country: "Germany",
    bodyType: "Sedan",
    engine: "3.0L Turbo V6 (EA839)",
    engineType: "Turbo",
    horsepower: 354,
    torqueNm: 500,
    zeroToHundred: 4.7,
    topSpeed: 250,
    drivetrain: "quattro AWD",
    weightKg: 1630,
    perfCategory: "Luxury",
    categories: ["European", "Luxury"],
    description: "The B9 S4 replaced its supercharged V6 with a torquey turbo unit, delivering discreet all-weather performance in a refined everyday saloon.",
    query: "Audi S4 (B9)",
    fallbackQuery: "Audi S4"
  },
  {
    id: "audi-rs-etron-gt",
    brand: "Audi",
    model: "RS e-tron GT",
    year: 2021,
    country: "Germany",
    bodyType: "Sedan",
    engine: "Dual Electric Motors (93.4 kWh)",
    engineType: "Electric",
    horsepower: 646,
    torqueNm: 830,
    zeroToHundred: 3.3,
    topSpeed: 250,
    drivetrain: "AWD",
    weightKg: 2347,
    perfCategory: "Super",
    categories: ["European", "Electric"],
    description: "The RS e-tron GT is Audi's electric flagship, its dual motors and 800-volt architecture delivering silent, instant supercar acceleration.",
    query: "Audi RS e-tron GT",
    fallbackQuery: "Audi e-tron GT"
  }
];
