export default [
  {
    id: "toyota-2000gt",
    brand: "Toyota",
    model: "2000GT",
    year: 1967,
    country: "Japan",
    bodyType: "Coupe",
    engine: "2.0L Inline-Six (3M)",
    engineType: "Naturally Aspirated",
    horsepower: 150,
    torqueNm: 175,
    zeroToHundred: 8.6,
    topSpeed: 220,
    drivetrain: "RWD",
    weightKg: 1120,
    perfCategory: "Sport",
    categories: ["JDM", "Classic Cars"],
    description: "Japan's first true supercar, the hand-built 2000GT stunned the world with its long hood and Yamaha-tuned straight-six.",
    query: "Toyota 2000GT",
    fallbackQuery: "Toyota 2000 GT"
  },
  {
    id: "toyota-corolla-levin-ae86",
    brand: "Toyota",
    model: "Corolla Levin AE86",
    year: 1983,
    country: "Japan",
    bodyType: "Coupe",
    engine: "1.6L Inline-Four (4A-GE)",
    engineType: "Naturally Aspirated",
    horsepower: 130,
    torqueNm: 149,
    zeroToHundred: 8.3,
    topSpeed: 195,
    drivetrain: "RWD",
    weightKg: 940,
    perfCategory: "Sport",
    categories: ["JDM", "Classic Cars"],
    description: "The featherweight rear-drive hachiroku that became a drifting legend thanks to its rev-happy 4A-GE and perfect balance.",
    query: "Toyota Corolla Levin AE86",
    fallbackQuery: "Toyota AE86"
  },
  {
    id: "toyota-supra-a80",
    brand: "Toyota",
    model: "Supra (A80)",
    year: 1993,
    country: "Japan",
    bodyType: "Coupe",
    engine: "3.0L Twin-Turbo Inline-Six (2JZ-GTE)",
    engineType: "Twin-Turbo",
    horsepower: 320,
    torqueNm: 451,
    zeroToHundred: 4.9,
    topSpeed: 285,
    drivetrain: "RWD",
    weightKg: 1570,
    perfCategory: "Sport",
    categories: ["JDM", "Classic Cars"],
    description: "The fourth-generation Supra paired a bulletproof 2JZ-GTE with muscular curves, becoming the tuner world's most revered icon.",
    query: "Toyota Supra A80",
    fallbackQuery: "Toyota Supra"
  },
  {
    id: "toyota-celica-gt-four-st185",
    brand: "Toyota",
    model: "Celica GT-Four (ST185)",
    year: 1989,
    country: "Japan",
    bodyType: "Coupe",
    engine: "2.0L Turbo Inline-Four (3S-GTE)",
    engineType: "Turbo",
    horsepower: 225,
    torqueNm: 304,
    zeroToHundred: 6.1,
    topSpeed: 240,
    drivetrain: "AWD",
    weightKg: 1460,
    perfCategory: "Sport",
    categories: ["JDM", "Classic Cars"],
    description: "Toyota's rally homologation special, the ST185 Celica GT-Four brought all-wheel drive and turbo boost to the World Rally stage.",
    query: "Toyota Celica GT-Four ST185",
    fallbackQuery: "Toyota Celica GT-Four"
  },
  {
    id: "toyota-mr2-sw20",
    brand: "Toyota",
    model: "MR2 (SW20)",
    year: 1989,
    country: "Japan",
    bodyType: "Coupe",
    engine: "2.0L Turbo Inline-Four (3S-GTE)",
    engineType: "Turbo",
    horsepower: 200,
    torqueNm: 275,
    zeroToHundred: 6.1,
    topSpeed: 240,
    drivetrain: "RWD",
    weightKg: 1260,
    perfCategory: "Sport",
    categories: ["JDM", "Classic Cars"],
    description: "The second-generation MR2 delivered mid-engine balance and turbocharged punch in a shape many called a baby Ferrari.",
    query: "Toyota MR2 SW20",
    fallbackQuery: "Toyota MR2"
  },
  {
    id: "toyota-yaris-gr",
    brand: "Toyota",
    model: "Yaris GR",
    year: 2020,
    country: "Japan",
    bodyType: "Hatchback",
    engine: "1.6L Turbo Inline-Three (G16E-GTS)",
    engineType: "Turbo",
    horsepower: 261,
    torqueNm: 360,
    zeroToHundred: 5.5,
    topSpeed: 230,
    drivetrain: "AWD",
    weightKg: 1280,
    perfCategory: "Sport",
    categories: ["JDM", "Track Cars"],
    description: "Built for rally homologation, the GR Yaris packs a 261-hp three-cylinder and clever all-wheel drive into a compact hatchback.",
    query: "Toyota GR Yaris",
    fallbackQuery: "Toyota Yaris GR"
  },
  {
    id: "toyota-land-cruiser-300",
    brand: "Toyota",
    model: "Land Cruiser 300",
    year: 2021,
    country: "Japan",
    bodyType: "SUV",
    engine: "3.5L Twin-Turbo V6 (V35A-FTS)",
    engineType: "Twin-Turbo",
    horsepower: 409,
    torqueNm: 650,
    zeroToHundred: 6.7,
    topSpeed: 210,
    drivetrain: "AWD",
    weightKg: 2495,
    perfCategory: "Luxury",
    categories: ["Luxury"],
    description: "The all-new Land Cruiser 300 traded V8 muscle for a twin-turbo V6 while keeping its legendary off-road durability intact.",
    query: "Toyota Land Cruiser 300",
    fallbackQuery: "Toyota Land Cruiser"
  },
  {
    id: "toyota-hilux",
    brand: "Toyota",
    model: "Hilux",
    year: 2015,
    country: "Japan",
    bodyType: "Pickup",
    engine: "2.8L Turbo Diesel Inline-Four (1GD-FTV)",
    engineType: "Turbo",
    horsepower: 177,
    torqueNm: 450,
    zeroToHundred: 10.5,
    topSpeed: 175,
    drivetrain: "4WD",
    weightKg: 2100,
    perfCategory: "Sport",
    categories: ["JDM"],
    description: "The eighth-generation Hilux reinforced its reputation as an indestructible workhorse, now with a torquey 2.8-litre diesel.",
    query: "Toyota Hilux",
    fallbackQuery: "Toyota Hilux 2016"
  },
  {
    id: "toyota-prius-xw50",
    brand: "Toyota",
    model: "Prius (XW50)",
    year: 2015,
    country: "Japan",
    bodyType: "Hatchback",
    engine: "1.8L Hybrid Inline-Four (2ZR-FXE)",
    engineType: "Hybrid",
    horsepower: 122,
    torqueNm: 142,
    zeroToHundred: 10.6,
    topSpeed: 180,
    drivetrain: "FWD",
    weightKg: 1375,
    perfCategory: "Luxury",
    categories: ["Electric"],
    description: "The fourth-generation Prius sharpened its styling and efficiency, pushing hybrid fuel economy to new heights for the masses.",
    query: "Toyota Prius XW50",
    fallbackQuery: "Toyota Prius"
  },
  {
    id: "nissan-fairlady-240z-s30",
    brand: "Nissan",
    model: "Fairlady 240Z (S30)",
    year: 1969,
    country: "Japan",
    bodyType: "Coupe",
    engine: "2.4L Inline-Six (L24)",
    engineType: "Naturally Aspirated",
    horsepower: 151,
    torqueNm: 198,
    zeroToHundred: 8.0,
    topSpeed: 201,
    drivetrain: "RWD",
    weightKg: 1068,
    perfCategory: "Sport",
    categories: ["JDM", "Classic Cars"],
    description: "The sleek 240Z proved a Japanese sports car could undercut European rivals on price while beating them on charm.",
    query: "Datsun 240Z",
    fallbackQuery: "Nissan Fairlady Z S30"
  },
  {
    id: "nissan-skyline-2000gt-r-hakosuka",
    brand: "Nissan",
    model: "Skyline 2000GT-R (Hakosuka)",
    year: 1969,
    country: "Japan",
    bodyType: "Sedan",
    engine: "2.0L Inline-Six (S20)",
    engineType: "Naturally Aspirated",
    horsepower: 160,
    torqueNm: 177,
    zeroToHundred: 8.2,
    topSpeed: 200,
    drivetrain: "RWD",
    weightKg: 1120,
    perfCategory: "Sport",
    categories: ["JDM", "Classic Cars"],
    description: "Nicknamed Hakosuka for its boxy shape, the first Skyline GT-R dominated Japanese touring car racing with its race-bred S20 six.",
    query: "Nissan Skyline 2000GT-R",
    fallbackQuery: "Nissan Skyline Hakosuka"
  },
  {
    id: "nissan-skyline-gt-r-r32",
    brand: "Nissan",
    model: "Skyline GT-R (R32)",
    year: 1989,
    country: "Japan",
    bodyType: "Coupe",
    engine: "2.6L Twin-Turbo Inline-Six (RB26DETT)",
    engineType: "Twin-Turbo",
    horsepower: 280,
    torqueNm: 353,
    zeroToHundred: 5.6,
    topSpeed: 250,
    drivetrain: "AWD",
    weightKg: 1430,
    perfCategory: "Sport",
    categories: ["JDM", "Classic Cars"],
    description: "Godzilla arrived with the R32 GT-R, whose RB26DETT and ATTESA all-wheel drive crushed all comers in Group A racing.",
    query: "Nissan Skyline GT-R R32",
    fallbackQuery: "Nissan Skyline GT-R"
  },
  {
    id: "nissan-skyline-gt-r-r34",
    brand: "Nissan",
    model: "Skyline GT-R (R34)",
    year: 1999,
    country: "Japan",
    bodyType: "Coupe",
    engine: "2.6L Twin-Turbo Inline-Six (RB26DETT)",
    engineType: "Twin-Turbo",
    horsepower: 280,
    torqueNm: 392,
    zeroToHundred: 5.0,
    topSpeed: 250,
    drivetrain: "AWD",
    weightKg: 1560,
    perfCategory: "Sport",
    categories: ["JDM", "Classic Cars"],
    description: "The R34 GT-R is the poster car of JDM culture, its aggressive stance and RB26DETT immortalised by film and video games.",
    query: "Nissan Skyline GT-R R34",
    fallbackQuery: "Nissan Skyline GT-R"
  },
  {
    id: "nissan-silvia-s15",
    brand: "Nissan",
    model: "Silvia S15",
    year: 1999,
    country: "Japan",
    bodyType: "Coupe",
    engine: "2.0L Turbo Inline-Four (SR20DET)",
    engineType: "Turbo",
    horsepower: 250,
    torqueNm: 275,
    zeroToHundred: 5.5,
    topSpeed: 235,
    drivetrain: "RWD",
    weightKg: 1240,
    perfCategory: "Sport",
    categories: ["JDM", "Track Cars"],
    description: "The final Silvia, the S15 combined a punchy SR20DET with rear-drive poise to become a drift and time-attack favourite.",
    query: "Nissan Silvia S15",
    fallbackQuery: "Nissan Silvia"
  },
  {
    id: "nissan-z-2022",
    brand: "Nissan",
    model: "Z",
    year: 2022,
    country: "Japan",
    bodyType: "Coupe",
    engine: "3.0L Twin-Turbo V6 (VR30DDTT)",
    engineType: "Twin-Turbo",
    horsepower: 400,
    torqueNm: 475,
    zeroToHundred: 4.5,
    topSpeed: 250,
    drivetrain: "RWD",
    weightKg: 1600,
    perfCategory: "Sport",
    categories: ["JDM"],
    description: "The reborn Nissan Z honours its heritage with retro styling and a 400-hp twin-turbo V6 driving the rear wheels.",
    query: "Nissan Z 2022",
    fallbackQuery: "Nissan Z"
  },
  {
    id: "nissan-leaf",
    brand: "Nissan",
    model: "Leaf",
    year: 2010,
    country: "Japan",
    bodyType: "Hatchback",
    engine: "80 kW Electric Motor",
    engineType: "Electric",
    horsepower: 109,
    torqueNm: 280,
    zeroToHundred: 11.5,
    topSpeed: 145,
    drivetrain: "FWD",
    weightKg: 1521,
    perfCategory: "Luxury",
    categories: ["Electric"],
    description: "The Leaf was the world's first mass-market electric car, bringing silent zero-emission driving to ordinary families.",
    query: "Nissan Leaf",
    fallbackQuery: "Nissan Leaf 2011"
  },
  {
    id: "nissan-patrol-y62",
    brand: "Nissan",
    model: "Patrol (Y62)",
    year: 2010,
    country: "Japan",
    bodyType: "SUV",
    engine: "5.6L V8 (VK56VD)",
    engineType: "Naturally Aspirated",
    horsepower: 400,
    torqueNm: 560,
    zeroToHundred: 7.5,
    topSpeed: 210,
    drivetrain: "4WD",
    weightKg: 2800,
    perfCategory: "Luxury",
    categories: ["Luxury"],
    description: "The Y62 Patrol swapped its rugged diesel for a 400-hp V8, blending desert-conquering ability with genuine luxury.",
    query: "Nissan Patrol Y62",
    fallbackQuery: "Nissan Patrol"
  },
  {
    id: "nissan-skyline-r31",
    brand: "Nissan",
    model: "Skyline (R31)",
    year: 1985,
    country: "Japan",
    bodyType: "Sedan",
    engine: "2.0L Turbo Inline-Six (RB20DET)",
    engineType: "Turbo",
    horsepower: 190,
    torqueNm: 245,
    zeroToHundred: 7.0,
    topSpeed: 220,
    drivetrain: "RWD",
    weightKg: 1300,
    perfCategory: "Sport",
    categories: ["JDM", "Classic Cars"],
    description: "The boxy R31 Skyline introduced the RB engine family and the GT-R's spiritual successor, the GTS-R.",
    query: "Nissan Skyline R31",
    fallbackQuery: "Nissan Skyline"
  },
  {
    id: "honda-nsx-na1",
    brand: "Honda",
    model: "NSX (NA1)",
    year: 1990,
    country: "Japan",
    bodyType: "Coupe",
    engine: "3.0L V6 (C30A)",
    engineType: "Naturally Aspirated",
    horsepower: 274,
    torqueNm: 285,
    zeroToHundred: 5.7,
    topSpeed: 270,
    drivetrain: "RWD",
    weightKg: 1370,
    perfCategory: "Super",
    categories: ["JDM", "Classic Cars"],
    description: "Developed with Ayrton Senna's input, the aluminium-bodied NSX rewrote the supercar rulebook with everyday usability.",
    query: "Honda NSX NA1",
    fallbackQuery: "Honda NSX"
  },
  {
    id: "honda-nsx-nc1",
    brand: "Honda",
    model: "NSX (NC1)",
    year: 2016,
    country: "Japan",
    bodyType: "Coupe",
    engine: "3.5L Twin-Turbo V6 Hybrid (JNC1)",
    engineType: "Hybrid",
    horsepower: 581,
    torqueNm: 646,
    zeroToHundred: 2.9,
    topSpeed: 307,
    drivetrain: "AWD",
    weightKg: 1725,
    perfCategory: "Super",
    categories: ["JDM", "Electric"],
    description: "The second-generation NSX fused a twin-turbo V6 with three electric motors for a 581-hp hybrid all-wheel-drive supercar.",
    query: "Honda NSX NC1",
    fallbackQuery: "Honda NSX 2016"
  },
  {
    id: "honda-s2000",
    brand: "Honda",
    model: "S2000",
    year: 1999,
    country: "Japan",
    bodyType: "Roadster",
    engine: "2.0L Inline-Four (F20C)",
    engineType: "Naturally Aspirated",
    horsepower: 240,
    torqueNm: 208,
    zeroToHundred: 6.2,
    topSpeed: 240,
    drivetrain: "RWD",
    weightKg: 1250,
    perfCategory: "Sport",
    categories: ["JDM", "Classic Cars"],
    description: "The S2000's F20C revved to 9000 rpm, delivering one of the purest open-top driving experiences ever built.",
    query: "Honda S2000",
    fallbackQuery: "Honda S2000 AP1"
  },
  {
    id: "honda-integra-type-r-dc2",
    brand: "Honda",
    model: "Integra Type R (DC2)",
    year: 1995,
    country: "Japan",
    bodyType: "Coupe",
    engine: "1.8L Inline-Four (B18C)",
    engineType: "Naturally Aspirated",
    horsepower: 200,
    torqueNm: 178,
    zeroToHundred: 6.7,
    topSpeed: 233,
    drivetrain: "FWD",
    weightKg: 1100,
    perfCategory: "Sport",
    categories: ["JDM", "Track Cars"],
    description: "The DC2 Integra Type R is widely hailed as the finest front-wheel-drive chassis ever made, its B18C screaming to 8400 rpm.",
    query: "Honda Integra Type R DC2",
    fallbackQuery: "Honda Integra Type R"
  },
  {
    id: "honda-civic-type-r-ek9",
    brand: "Honda",
    model: "Civic Type R (EK9)",
    year: 1997,
    country: "Japan",
    bodyType: "Hatchback",
    engine: "1.6L Inline-Four (B16B)",
    engineType: "Naturally Aspirated",
    horsepower: 185,
    torqueNm: 160,
    zeroToHundred: 6.7,
    topSpeed: 225,
    drivetrain: "FWD",
    weightKg: 1070,
    perfCategory: "Sport",
    categories: ["JDM", "Track Cars"],
    description: "The first Civic Type R, the EK9 paired a hand-ported B16B with a seam-welded body for razor-sharp track manners.",
    query: "Honda Civic Type R EK9",
    fallbackQuery: "Honda Civic Type R"
  },
  {
    id: "honda-cr-x",
    brand: "Honda",
    model: "CR-X",
    year: 1983,
    country: "Japan",
    bodyType: "Coupe",
    engine: "1.5L Inline-Four (EW)",
    engineType: "Naturally Aspirated",
    horsepower: 91,
    torqueNm: 126,
    zeroToHundred: 9.5,
    topSpeed: 180,
    drivetrain: "FWD",
    weightKg: 860,
    perfCategory: "Sport",
    categories: ["JDM", "Classic Cars"],
    description: "The original CR-X was a featherweight, fuel-sipping coupe whose slippery shape and light chassis made it a joy to drive.",
    query: "Honda CR-X",
    fallbackQuery: "Honda CRX"
  },
  {
    id: "honda-accord-type-r",
    brand: "Honda",
    model: "Accord Type R",
    year: 1998,
    country: "Japan",
    bodyType: "Sedan",
    engine: "2.2L Inline-Four (H22A)",
    engineType: "Naturally Aspirated",
    horsepower: 212,
    torqueNm: 215,
    zeroToHundred: 6.9,
    topSpeed: 235,
    drivetrain: "FWD",
    weightKg: 1350,
    perfCategory: "Sport",
    categories: ["JDM", "Track Cars"],
    description: "The European-market Accord Type R hid a 212-hp H22A and limited-slip differential inside a discreet four-door body.",
    query: "Honda Accord Type R",
    fallbackQuery: "Honda Accord"
  },
  {
    id: "honda-s660",
    brand: "Honda",
    model: "S660",
    year: 2015,
    country: "Japan",
    bodyType: "Roadster",
    engine: "0.66L Turbo Inline-Three (S07A)",
    engineType: "Turbo",
    horsepower: 64,
    torqueNm: 104,
    zeroToHundred: 11.0,
    topSpeed: 140,
    drivetrain: "RWD",
    weightKg: 830,
    perfCategory: "Sport",
    categories: ["JDM"],
    description: "The mid-engined S660 revived kei-car sports motoring with a tiny turbo triple and a chassis tuned for pure balance.",
    query: "Honda S660",
    fallbackQuery: "Honda S660 2015"
  },
  {
    id: "honda-cr-v",
    brand: "Honda",
    model: "CR-V",
    year: 2016,
    country: "Japan",
    bodyType: "SUV",
    engine: "1.5L Turbo Inline-Four (L15B7)",
    engineType: "Turbo",
    horsepower: 190,
    torqueNm: 243,
    zeroToHundred: 8.5,
    topSpeed: 200,
    drivetrain: "AWD",
    weightKg: 1560,
    perfCategory: "Luxury",
    categories: ["Luxury"],
    description: "The fifth-generation CR-V refined the compact crossover formula with a punchy turbo engine and generous cabin space.",
    query: "Honda CR-V 2017",
    fallbackQuery: "Honda CR-V"
  }
];
