export default [
  {
    id: "tesla-roadster-2008",
    brand: "Tesla",
    model: "Roadster",
    year: 2008,
    country: "United States",
    bodyType: "Roadster",
    engine: "Single-Motor Electric",
    engineType: "Electric",
    horsepower: 248,
    torqueNm: 370,
    zeroToHundred: 3.9,
    topSpeed: 201,
    drivetrain: "RWD",
    weightKg: 1305,
    perfCategory: "Sport",
    categories: ["Electric"],
    description: "The Lotus-derived roadster that started it all, proving electric cars could be fast, desirable and genuinely fun to drive.",
    query: "Tesla Roadster 2008",
    fallbackQuery: "Tesla Roadster"
  },
  {
    id: "tesla-model-s-2012",
    brand: "Tesla",
    model: "Model S",
    year: 2012,
    country: "United States",
    bodyType: "Sedan",
    engine: "Single-Motor Electric",
    engineType: "Electric",
    horsepower: 362,
    torqueNm: 440,
    zeroToHundred: 5.4,
    topSpeed: 201,
    drivetrain: "RWD",
    weightKg: 2108,
    perfCategory: "Luxury",
    categories: ["Electric", "Luxury"],
    description: "Tesla's sleek liftback sedan rewrote the luxury rulebook with a giant touchscreen, over-the-air updates and silent instant thrust.",
    query: "Tesla Model S 2012",
    fallbackQuery: "Tesla Model S"
  },
  {
    id: "tesla-model-3-perf",
    brand: "Tesla",
    model: "Model 3 Performance",
    year: 2019,
    country: "United States",
    bodyType: "Sedan",
    engine: "Dual-Motor Electric",
    engineType: "Electric",
    horsepower: 450,
    torqueNm: 639,
    zeroToHundred: 3.3,
    topSpeed: 261,
    drivetrain: "AWD",
    weightKg: 1847,
    perfCategory: "Sport",
    categories: ["Electric"],
    description: "The dual-motor Model 3 Performance turned the everyday electric sedan into a track-capable giant-killer with supercar-humbling acceleration.",
    query: "Tesla Model 3 Performance",
    fallbackQuery: "Tesla Model 3"
  },
  {
    id: "tesla-model-3-rwd",
    brand: "Tesla",
    model: "Model 3 RWD",
    year: 2017,
    country: "United States",
    bodyType: "Sedan",
    engine: "Single-Motor Electric",
    engineType: "Electric",
    horsepower: 271,
    torqueNm: 404,
    zeroToHundred: 5.6,
    topSpeed: 225,
    drivetrain: "RWD",
    weightKg: 1645,
    perfCategory: "Sport",
    categories: ["Electric"],
    description: "The affordable rear-drive Model 3 brought long-range electric motoring to the masses with minimalist design and brisk single-motor pace.",
    query: "Tesla Model 3",
    fallbackQuery: "Tesla Model 3 RWD"
  },
  {
    id: "tesla-model-x-plaid",
    brand: "Tesla",
    model: "Model X Plaid",
    year: 2021,
    country: "United States",
    bodyType: "SUV",
    engine: "Tri-Motor Electric",
    engineType: "Electric",
    horsepower: 1020,
    torqueNm: 1424,
    zeroToHundred: 2.6,
    topSpeed: 262,
    drivetrain: "AWD",
    weightKg: 2465,
    perfCategory: "Super",
    categories: ["Electric", "Luxury"],
    description: "Falcon-wing doors and a tri-motor Plaid powertrain make this seven-seat SUV one of the quickest vehicles ever built.",
    query: "Tesla Model X Plaid",
    fallbackQuery: "Tesla Model X"
  },
  {
    id: "tesla-model-y-perf",
    brand: "Tesla",
    model: "Model Y Performance",
    year: 2020,
    country: "United States",
    bodyType: "SUV",
    engine: "Dual-Motor Electric",
    engineType: "Electric",
    horsepower: 456,
    torqueNm: 674,
    zeroToHundred: 3.5,
    topSpeed: 250,
    drivetrain: "AWD",
    weightKg: 1995,
    perfCategory: "Sport",
    categories: ["Electric"],
    description: "The crossover version of the Model 3 adds dual-motor grip and a raised body, blending family practicality with startling straight-line speed.",
    query: "Tesla Model Y Performance",
    fallbackQuery: "Tesla Model Y"
  },
  {
    id: "tesla-cybertruck",
    brand: "Tesla",
    model: "Cybertruck",
    year: 2023,
    country: "United States",
    bodyType: "Pickup",
    engine: "Tri-Motor Electric",
    engineType: "Electric",
    horsepower: 845,
    torqueNm: 1184,
    zeroToHundred: 2.9,
    topSpeed: 209,
    drivetrain: "AWD",
    weightKg: 3104,
    perfCategory: "Super",
    categories: ["Electric"],
    description: "Its angular stainless-steel exoskeleton and tri-motor Cyberbeast drivetrain make this polarising pickup brutally quick off the line.",
    query: "Tesla Cybertruck",
    fallbackQuery: "Tesla Cybertruck Cyberbeast"
  },
  {
    id: "tesla-semi",
    brand: "Tesla",
    model: "Semi",
    year: 2022,
    country: "United States",
    bodyType: "Pickup",
    engine: "Tri-Motor Electric",
    engineType: "Electric",
    horsepower: 1020,
    torqueNm: 1424,
    zeroToHundred: 6.3,
    topSpeed: 113,
    drivetrain: "AWD",
    weightKg: 10433,
    perfCategory: "Sport",
    categories: ["Electric"],
    description: "Tesla's battery-electric Class 8 tractor hauls 82,000 pounds while out-accelerating most diesel semis and climbing grades with ease.",
    query: "Tesla Semi",
    fallbackQuery: "Tesla Semi truck"
  },
  {
    id: "tesla-roadster-2nd-gen",
    brand: "Tesla",
    model: "Roadster (2nd Gen)",
    year: 2020,
    country: "United States",
    bodyType: "Roadster",
    engine: "Tri-Motor Electric",
    engineType: "Electric",
    horsepower: 772,
    torqueNm: 10000,
    zeroToHundred: 2.1,
    topSpeed: 400,
    drivetrain: "AWD",
    weightKg: 2000,
    perfCategory: "Hyper",
    categories: ["Electric", "Supercars"],
    description: "The second-generation Roadster promises hypercar-shattering acceleration, a 620-mile range and an optional SpaceX cold-gas thruster package.",
    query: "Tesla Roadster second generation",
    fallbackQuery: "Tesla Roadster 2020"
  },
  {
    id: "mazda-cosmo-sport-110s",
    brand: "Mazda",
    model: "Cosmo Sport 110S",
    year: 1967,
    country: "Japan",
    bodyType: "Coupe",
    engine: "0.98L Twin-Rotor (10A)",
    engineType: "Rotary",
    horsepower: 110,
    torqueNm: 130,
    zeroToHundred: 8.8,
    topSpeed: 185,
    drivetrain: "RWD",
    weightKg: 940,
    perfCategory: "Sport",
    categories: ["JDM", "Classic Cars"],
    description: "Mazda's pioneering twin-rotor coupe, the Cosmo Sport 110S proved the Wankel engine could power a genuinely desirable sports car.",
    query: "Mazda Cosmo Sport",
    fallbackQuery: "Mazda Cosmo 110S"
  },
  {
    id: "mazda-rx3-savanna",
    brand: "Mazda",
    model: "RX-3 Savanna",
    year: 1971,
    country: "Japan",
    bodyType: "Coupe",
    engine: "1.0L Twin-Rotor (10A)",
    engineType: "Rotary",
    horsepower: 110,
    torqueNm: 135,
    zeroToHundred: 9.3,
    topSpeed: 180,
    drivetrain: "RWD",
    weightKg: 880,
    perfCategory: "Sport",
    categories: ["JDM", "Classic Cars"],
    description: "The lightweight rotary Savanna coupe dominated Japanese touring car racing, earning Mazda a fearsome reputation on track.",
    query: "Mazda RX-3 Savanna",
    fallbackQuery: "Mazda RX-3"
  },
  {
    id: "mazda-mx5-na",
    brand: "Mazda",
    model: "MX-5 Miata (NA)",
    year: 1989,
    country: "Japan",
    bodyType: "Roadster",
    engine: "1.6L Inline-Four (B6ZE)",
    engineType: "Naturally Aspirated",
    horsepower: 116,
    torqueNm: 136,
    zeroToHundred: 8.6,
    topSpeed: 195,
    drivetrain: "RWD",
    weightKg: 950,
    perfCategory: "Sport",
    categories: ["JDM", "Classic Cars"],
    description: "The featherweight NA Miata revived the affordable British roadster formula with perfect balance, pop-up lights and endless charm.",
    query: "Mazda MX-5 NA",
    fallbackQuery: "Mazda Miata NA"
  },
  {
    id: "mazda-mx5-nd",
    brand: "Mazda",
    model: "MX-5 Miata (ND)",
    year: 2015,
    country: "Japan",
    bodyType: "Roadster",
    engine: "2.0L Inline-Four (SKYACTIV-G)",
    engineType: "Naturally Aspirated",
    horsepower: 155,
    torqueNm: 200,
    zeroToHundred: 7.3,
    topSpeed: 214,
    drivetrain: "RWD",
    weightKg: 1050,
    perfCategory: "Sport",
    categories: ["JDM"],
    description: "The fourth-generation MX-5 shed weight and gained sharp SKYACTIV responses, keeping the roadster recipe pure and joyfully simple.",
    query: "Mazda MX-5 ND",
    fallbackQuery: "Mazda MX-5 2015"
  },
  {
    id: "mazda-rx8",
    brand: "Mazda",
    model: "RX-8",
    year: 2003,
    country: "Japan",
    bodyType: "Coupe",
    engine: "1.3L Twin-Rotor Renesis (13B-MSP)",
    engineType: "Rotary",
    horsepower: 231,
    torqueNm: 211,
    zeroToHundred: 6.4,
    topSpeed: 235,
    drivetrain: "RWD",
    weightKg: 1350,
    perfCategory: "Sport",
    categories: ["JDM"],
    description: "The four-seat RX-8 paired a screaming naturally aspirated Renesis rotary with freestyle rear doors and near-perfect 50:50 balance.",
    query: "Mazda RX-8",
    fallbackQuery: "Mazda RX8"
  },
  {
    id: "mazda3-mps",
    brand: "Mazda",
    model: "Mazda3 MPS",
    year: 2006,
    country: "Japan",
    bodyType: "Hatchback",
    engine: "2.3L Turbo Inline-Four (DISI)",
    engineType: "Turbo",
    horsepower: 260,
    torqueNm: 380,
    zeroToHundred: 6.1,
    topSpeed: 250,
    drivetrain: "FWD",
    weightKg: 1385,
    perfCategory: "Sport",
    categories: ["JDM"],
    description: "The torque-steering Mazdaspeed3 hot hatch packed a 260-horsepower turbo four into a practical five-door, terrorising bigger performance cars.",
    query: "Mazda3 MPS",
    fallbackQuery: "Mazdaspeed3"
  },
  {
    id: "mazda6-mps",
    brand: "Mazda",
    model: "Mazda6 MPS",
    year: 2005,
    country: "Japan",
    bodyType: "Sedan",
    engine: "2.3L Turbo Inline-Four (DISI)",
    engineType: "Turbo",
    horsepower: 260,
    torqueNm: 380,
    zeroToHundred: 5.7,
    topSpeed: 240,
    drivetrain: "AWD",
    weightKg: 1590,
    perfCategory: "Sport",
    categories: ["JDM"],
    description: "The Mazdaspeed6 hid a 260-horsepower turbo four and all-wheel drive under a sober sedan body, delivering discreet four-door muscle.",
    query: "Mazda6 MPS",
    fallbackQuery: "Mazdaspeed6"
  },
  {
    id: "mazda-cx5",
    brand: "Mazda",
    model: "CX-5",
    year: 2017,
    country: "Japan",
    bodyType: "SUV",
    engine: "2.5L Inline-Four (SKYACTIV-G)",
    engineType: "Naturally Aspirated",
    horsepower: 187,
    torqueNm: 251,
    zeroToHundred: 8.6,
    topSpeed: 200,
    drivetrain: "AWD",
    weightKg: 1658,
    perfCategory: "Luxury",
    categories: ["JDM"],
    description: "The second-generation CX-5 brought premium design and sharp G-Vectoring handling to the compact crossover class with efficient SKYACTIV power.",
    query: "Mazda CX-5",
    fallbackQuery: "Mazda CX5"
  },
  {
    id: "mazda2",
    brand: "Mazda",
    model: "Mazda2",
    year: 2014,
    country: "Japan",
    bodyType: "Hatchback",
    engine: "1.5L Inline-Four (SKYACTIV-G)",
    engineType: "Naturally Aspirated",
    horsepower: 100,
    torqueNm: 133,
    zeroToHundred: 10.4,
    topSpeed: 184,
    drivetrain: "FWD",
    weightKg: 1046,
    perfCategory: "Sport",
    categories: ["JDM"],
    description: "The tiny Mazda2 supermini punches above its weight with eager SKYACTIV handling, light kerb weight and surprising urban agility.",
    query: "Mazda2",
    fallbackQuery: "Mazda 2 hatchback"
  }
];
