// Generate src/data/catalog.ts from the authored specs + fetched image metadata.
// Run after scripts/fetch-catalog.mjs has downloaded the Commons photos.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const GROUPS = ["group-a", "group-b", "group-c", "group-d", "group-e", "group-f"];
const META_PATH = join(ROOT, "scratch", "catalog-meta.json");
const IMAGE_DIR = join(ROOT, "public", "cars");
const OUT_PATH = join(ROOT, "src", "data", "catalog.ts");

const meta = existsSync(META_PATH) ? JSON.parse(readFileSync(META_PATH, "utf8")) : {};

const specs = [];
for (const group of GROUPS) {
  const mod = await import(
    `file://${join(ROOT, "scripts", "spec", `${group}.mjs`).replace(/\\/g, "/")}`
  );
  specs.push(...mod.default);
}

const ids = new Set();
const cars = [];
const missing = [];

for (const spec of specs) {
  if (ids.has(spec.id)) throw new Error(`duplicate id: ${spec.id}`);
  ids.add(spec.id);

  const file = `${spec.id}.jpg`;
  const record = meta[spec.id];
  if (!record || !existsSync(join(IMAGE_DIR, file))) {
    missing.push(spec.id);
    continue;
  }

  cars.push({
    id: spec.id,
    brand: spec.brand,
    model: spec.model,
    year: spec.year,
    country: spec.country,
    bodyType: spec.bodyType,
    engine: spec.engine,
    engineType: spec.engineType,
    horsepower: spec.horsepower,
    torqueNm: spec.torqueNm,
    zeroToHundred: spec.zeroToHundred,
    topSpeed: spec.topSpeed,
    drivetrain: spec.drivetrain,
    weightKg: spec.weightKg,
    description: spec.description,
    categories: spec.categories,
    perfCategory: spec.perfCategory,
    image: `/cars/${file}`,
    gallery: [`/cars/${file}`],
    credits: [
      {
        image: file,
        artist: record.artist,
        license: record.license,
        url: record.page,
      },
    ],
  });
}

const q = (value) => JSON.stringify(value);
const lines = [];
for (const car of cars) {
  lines.push("  {");
  lines.push(`    id: ${q(car.id)},`);
  lines.push(`    brand: ${q(car.brand)},`);
  lines.push(`    model: ${q(car.model)},`);
  lines.push(`    year: ${car.year},`);
  lines.push(`    country: ${q(car.country)},`);
  lines.push(`    bodyType: ${q(car.bodyType)},`);
  lines.push(`    engine: ${q(car.engine)},`);
  lines.push(`    engineType: ${q(car.engineType)},`);
  lines.push(`    horsepower: ${car.horsepower},`);
  lines.push(`    torqueNm: ${car.torqueNm},`);
  lines.push(`    zeroToHundred: ${car.zeroToHundred},`);
  lines.push(`    topSpeed: ${car.topSpeed},`);
  lines.push(`    drivetrain: ${q(car.drivetrain)},`);
  lines.push(`    weightKg: ${car.weightKg},`);
  lines.push(`    description: ${q(car.description)},`);
  lines.push(`    categories: [${car.categories.map(q).join(", ")}],`);
  lines.push(`    perfCategory: ${q(car.perfCategory)},`);
  lines.push(`    image: ${q(car.image)},`);
  lines.push(`    gallery: [${car.gallery.map(q).join(", ")}],`);
  lines.push(`    credits: [`);
  for (const credit of car.credits) {
    lines.push(
      `      { image: ${q(credit.image)}, artist: ${q(credit.artist)}, license: ${q(credit.license)}, url: ${q(credit.url)} },`,
    );
  }
  lines.push(`    ],`);
  lines.push(`  },`);
}

const output = `// Generated by scripts/gen-catalog.mjs — do not edit by hand.
// Source: scripts/spec/group-*.mjs + scratch/catalog-meta.json (Wikimedia Commons).
import type { Car } from "./cars";

export const CATALOG_CARS: Car[] = [
${lines.join("\n")}
];
`;

writeFileSync(OUT_PATH, output);

console.log(`specs=${specs.length} written=${cars.length} missing=${missing.length}`);
if (missing.length > 0) console.log(`missing images: ${missing.join(", ")}`);
